.env.example
README.md

Just to help people get up and running.

Add a basic setup README and a starting .env example.

---

src/__tests__/index.test.tsx
src/components/media/index.test.tsx
src/components/media/index.tsx
src/components/node/person_profile/index.tsx
src/pages/demo/media/index.tsx
src/pages/demo/partials/benefitHubsLinks.tsx

The media image component is built to accept an image style that allows users to pass a prop to modify the image size.
- 1_1_square_medium_thumbnail:
- 2_1_large 
- 2_1_medium_thumbnail
- 2_3_medium_thumbnail
- 3_2_medium_thumbnail
- 7_2_medium_thumbnail
- full_content_width
- large
- self
- viewport_width

VA-8676 Component Media--image 

---

src/components/paragraph/button/index.test.tsx
src/components/paragraph/button/index.tsx
src/pages/demo/button/index.tsx

[WIP] 8610 paragraph--button implementation

---

src/pages/index.tsx

Demo components Stub

---

src/components/paragraph/button/index.tsx
src/pages/index.tsx

Just a quick link fix that I missed on the media component

media-link bugfix

---

src/components/paragraph/button/index.tsx
src/components/paragraph/email_contact/index.test.tsx
src/components/paragraph/email_contact/index.tsx
src/components/paragraph/expandable_text/index.test.tsx
src/components/paragraph/expandable_text/index.tsx
src/pages/demo/button/index.tsx
src/pages/demo/emailContacts/index.tsx
src/pages/demo/expandableText/index.tsx
src/types/node.d.ts

VACMS 8615 expandable_text component

---

.gitignore
READMEs/code-guidelines.md
package.json
src/components/node/index.tsx
src/components/node/news_story/index.tsx
src/types/node.d.ts
tsconfig.json
yarn.lock

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8433

Basic Typedoc implementation and readme.

---

READMEs/typescript.md

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8968

Starter README for Typescript.

---

src/components/footer/helpers.test.js
src/components/node/news_story/index.test.tsx
src/components/node/news_story/index.tsx
src/components/node/news_story/mock.json
src/components/paragraph/audience_topics/index.tsx
src/pages/index.tsx
src/utils/utils.ts

- Added unit test to test that the news story mounts with the correct view mode param passed to the component
- Created mock json file for the test
Open questions: where do we want mock json to live? should it be relative to the component?

Add unit test to news story

---

src/components/node/index.tsx
src/components/node/q_a/index.tsx
src/components/partials/benefitHubsLinks/index.tsx
src/pages/demo/partials/benefitHubsLinks.tsx

Node QA Initial Pass

---

package.json
src/components/node/index.tsx
src/components/node/news_story/index.test.tsx
src/components/node/person_profile/index.tsx
src/components/node/q_a/index.tsx
src/components/paragraph/audience_topics/index.tsx
src/components/paragraph/button/index.test.tsx
src/components/paragraph/button/index.tsx
src/components/paragraph/email_contact/index.test.tsx
src/components/paragraph/email_contact/index.tsx
src/components/paragraph/expandable_text/index.test.tsx
src/components/paragraph/expandable_text/index.tsx
src/components/paragraph/index.test.tsx
src/components/paragraph/index.tsx
src/components/paragraph/link_teaser/index.test.tsx
src/components/paragraph/link_teaser/index.tsx
src/components/paragraph/staff_profile/index.tsx
src/pages/demo/audienceTopics/index.tsx
src/pages/demo/button/index.tsx
src/pages/demo/emailContacts/index.tsx
src/pages/demo/expandableText/index.tsx
src/pages/demo/linkTeasers/index.tsx
src/pages/demo/personProfiles/index.tsx
src/pages/index.tsx
src/types/node.d.ts
src/types/paragraph.d.ts
yarn.lock

- created a Paragraph component to delegate which component to render based on the Paragraph data.
- Fixed lint errors on the news_story tests

VACMS-9129 abstract Paragraph component

---

package.json
src/utils/drupalClient.ts
yarn.lock

Latest release of next-drupal is now stable

Bump next drupal to stable version

---

package.json
src/components/footer/helpers.tsx
src/components/footer/index.test.jsx
src/components/layout/index.test.tsx
src/components/layout/index.tsx
src/components/paragraph/index.tsx
src/components/paragraph/wysiwyg/index.test.tsx
src/components/paragraph/wysiwyg/index.tsx
src/mocks/mockFetch.ts
src/pages/_app.tsx
src/pages/demo/wysiwyg/index.tsx
src/pages/index.tsx
src/types/paragraph.ts
src/utils/helpers.ts
yarn.lock

VACMS |  Platform | 8642
-------------------------
Screenshot: 
Drupal to VA Path Filter https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/filters/liquid.js#L112
```
liquid.filters.drupalToVaPath = content => {
let replaced = content;
if (content) {
replaced = content.replace(/href="(.*?)(png|jpg|jpeg|svg|gif)"/g, img =>
img
.replace('http://va-gov-cms.lndo.site/sites/default/files', '/img')
.replace('http://dev.cms.va.gov/sites/default/files', '/img')
.replace('http://staging.cms.va.gov/sites/default/files', '/img')
.replace('http://prod.cms.va.gov/sites/default/files', '/img')
.replace('https://prod.cms.va.gov/sites/default/files', '/img')
.replace('http://cms.va.gov/sites/default/files', '/img')
.replace('https://cms.va.gov/sites/default/files', …
```

Paragraph--Wysiwyg Initial Commit

---

additional.d.ts
package.json
src/components/layout/index.test.tsx
src/components/layout/index.tsx
src/components/node/banner/index.tsx
src/components/node/banner_alert/index.test.tsx
src/components/node/banner_alert/index.tsx
src/components/node/index.tsx
src/lib/context/getGlobalElements.test.ts
src/lib/context/getGlobalElements.ts
src/pages/[...slug].tsx
src/pages/index.tsx
src/utils/drupalClient.ts
yarn.lock

Set up global context for banners and footer
Pass context into layout
Determine if the user is on a slug route or the homepage

VACMS banner global context

---

.github/pull_request_template.md

a slightly modified version of the va.gov-cms's PR template. removed the parts that i felt weren't super relevant to our team & this repo

VAMCS-0000 add pr template to save time later

---

src/components/richTextCharLimit1000/index.test.tsx
src/components/richTextCharLimit1000/index.tsx
src/components/richTextCharLimit1000/rich_text_limit.stories.tsx
src/components/wysiwyg/index.test.tsx
src/components/wysiwyg/index.tsx
src/components/wysiwyg/wysiwyg.stories.tsx
src/pages/demo/wysiwyg/index.tsx

Relates to #10084
Run application and select Wysiwyg

VACMS-10084 Component Refactor: Wysiwyg

---

src/components/media/dataService.tsx
src/components/media/index.test.tsx
src/components/media/index.tsx
src/components/media/media.stories.tsx
src/components/newsStoryFull/dataService.tsx
src/components/newsStoryFull/index.test.tsx
src/components/newsStoryFull/index.tsx
src/components/newsStoryTeaser/dataService.tsx
src/components/newsStoryTeaser/index.test.tsx
src/components/newsStoryTeaser/index.tsx
src/components/person_profile/dataService.tsx
src/components/person_profile/index.tsx
src/components/staffProfile/dataService.tsx
src/components/staffProfile/index.tsx
src/components/story_listing/dataService.tsx
src/lib/delegators/entityMetaProvider.tsx
src/pages/demo/media/index.tsx

Fixes image display 
Relates to #_issueid_. (or closes?)
As user _uid_ with _user_role_
1. Do this
2. Then
3. Then validate Acceptance Criteria from issue

Fix media image

---

package.json
src/lib/utils/date.test.ts
src/lib/utils/date.ts
src/lib/utils/medallia.ts
src/pages/[[...slug]].tsx
src/templates/common/contentFooter/contentFooter.stories.tsx
src/templates/common/contentFooter/index.tsx
src/templates/globals/medallia/index.tsx
src/templates/layouts/newsStory/index.tsx
src/types/index.d.ts

Relates to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14830
- This PR includes a test suite for the date utilities added.
- This PR adds Storybook entries for the ContentFooter component to help ensure accuracy and demonstrate the API.
- The component can be seen on a real page here: `/minneapolis-health-care/stories/challenging-advanced-dementia-patients-often-need-a-bro/`

VACMS-14830: Content Footer

---

src/lib/drupal/listingPages.ts

Resolves https://github.com/department-of-veterans-affairs/next-build/security/code-scanning/74

Removes unused variable alerted in code scan 74

---

src/data/queries/mediaImage.ts

add safeguard for no media

---

.storybook/403-error-document.html
.storybook/README.md
.tugboat/config.yml
.tugboat/vhost-storybook.conf
package.json
src/data/queries/mediaImage.ts

Closes #[15382](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15382).
Edited nginx config via tugboat terminal, verified that the different domains resolve as expected
```[tasklist]
```

VACMS-15382 storybook available on tugboat

---

.prettierignore
.storybook/403-error-document.html

prettier fix that should have happened in #186 but didn't. hm.
CI tests should pass
```[tasklist]
```

prettier + update ignore

---

.github/workflows/packer-ghar.yml
packer/github-action-runner/builder.pkr.hcl
packer/github-action-runner/scripts/cleanup.sh
packer/github-action-runner/scripts/docker-prune-cron.sh
packer/github-action-runner/scripts/openssl-config.sh
packer/github-action-runner/scripts/playwright-dependencies.sh
packer/github-action-runner/scripts/runner-partition.sh
packer/github-action-runner/scripts/runner.sh
packer/github-action-runner/scripts/stig.sh
packer/github-action-runner/scripts/unregister-github-runners.sh
packer/github-action-runner/sources.pkr.hcl
packer/github-action-runner/variables.pkr.hcl

Add workflow and packer config to create custom self-hosted runners.
```[tasklist]
```

Next-Build Custom Self-hosted Runner

---

additional.d.ts
src/data/queries/accordion.ts
src/data/queries/index.ts
src/data/queries/tests/__snapshots__/accordion.test.tsx.snap
src/data/queries/tests/accordion.test.tsx
src/lib/utils/stringToId.test.ts
src/lib/utils/stringToId.ts
src/mocks/accordion.mock.json
src/templates/components/accordion/accordion.stories.ts
src/templates/components/accordion/index.test.tsx
src/templates/components/accordion/index.tsx
src/types/drupal/paragraph.ts
src/types/formatted/accordion.ts

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16740
- Adds basic paragraph component
- Adds query
- Adds types
- Adds tests
- Adds function for formatting accordion IDs
- NOTE-  expand all text does not work at the moment. See this DS ticket: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1620
- yarn test
- yarn test:types
- verified visually in storybook
Verify storybook that accordions render as expected
```[tasklist]
```

16740 basic accordion

---

additional.d.ts
src/data/queries/tests/__snapshots__/richTextCharLimit1000.test.tsx.snap
src/data/queries/tests/__snapshots__/wysiwyg.test.tsx.snap
src/data/queries/wysiwyg.ts
src/lib/constants/resourceTypes.ts
src/lib/utils/helpers.ts
src/lib/utils/slug.test.ts
src/lib/utils/slug.ts
src/templates/common/heading/index.tsx
src/templates/components/collapsiblePanel/collapsiblePanel.stories.ts
src/templates/components/collapsiblePanel/index.test.tsx
src/templates/components/collapsiblePanel/index.tsx
src/templates/components/paragraph/index.tsx
src/templates/components/table/index.test.tsx
src/templates/components/table/index.tsx
src/templates/components/wysiwyg/index.test.tsx
src/templates/components/wysiwyg/index.tsx
src/templates/components/wysiwyg/wysiwyg.stories.ts
src/types/formatted/collapsiblePanel.ts
src/types/formatted/headingElement.ts
src/types/formatted/paragraph.ts
src/types/formatted/publishedEntity.ts
src/types/formatted/table.ts
src/types/formatted/wysiwyg.ts

Relates to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8612
Renders component in Storybook
Storybook allows some ability to QA this PR. 
The more thorough QA will come with the follow-on work that encompasses using this template/component on Resources and Support pages. My preference is to merge this and then work from a clean `main` branch on the next steps. Considering this is not in production yet, the risk here is very low. The follow-on work will really be the place where we can see this in action, and where we'll start to understand some more constraints that might not be immediately obvious now.

VACMS-8612: Collapsible Panel paragraph template

---

.github/workflows/mirror-images.yml
.github/workflows/update-manifest.yml
docker-run.sh
docker/.dockerignore
docker/Dockerfile

Relates to #[16857](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16857). Adds Dockerfile for next-build container.
Docker container builds, full testing will require k8s env and additional config pieces there.
```[tasklist]
```

Initial pass at Dockerfile and supporting files

---

envs/.env.tugboat

Relates to https://github.com/department-of-veterans-affairs/va.gov-cms/pull/17154
```[tasklist]
```

update tugboat env file with port

---

.github/workflows/update-manifest.yml

Relates to #[16857](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16857)
```[tasklist]
```

Generalize params for manifest update environments

---

src/data/queries/contactInfo.ts
src/data/queries/index.ts
src/data/queries/phoneNumber.ts
src/data/queries/tests/__snapshots__/contactInfo.test.tsx.snap
src/data/queries/tests/__snapshots__/phoneNumber.test.tsx.snap
src/data/queries/tests/phoneNumber.test.tsx
src/mocks/phoneNumber.mock.json
src/types/formatted/contactInfo.ts

phone number paragraph formatter

---

envs/.env.example
packages/proxy-fetcher/src/index.ts

VACMS-0000 Set Proxy-fetcher to Only Run for Local ENVs

---

playwright/tests/eventListing.spec.js
src/data/queries/banners.ts

update event listing playwright test

---

.github/workflows/update-manifest.yml

Relates to #[16863](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16863). 
```[tasklist]
```

Update where image data should be modified

---

generator-templates/query/query.hbs
src/data/queries/alertSingle.ts
src/data/queries/contactInfo.ts
src/data/queries/event.ts
src/data/queries/eventListing.ts
src/data/queries/eventTeaser.ts
src/data/queries/headerFooter.ts
src/data/queries/mediaImage.ts
src/data/queries/newsStory.ts
src/data/queries/newsStoryTeaser.ts
src/data/queries/personProfile.ts
src/data/queries/promoBlock.ts
src/data/queries/questionAnswer.ts
src/data/queries/resourcesSupport.ts
src/data/queries/staticPathResources.ts
src/data/queries/storyListing.ts
src/data/queries/vamcEhr.ts
src/lib/drupal/query.ts
src/pages/_playground/api-explorer.tsx

Relates to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17335
Updates `params` function on queries to start with a fresh `DrupalJsonApiParams` object
See: https://dsva.slack.com/archives/C01SR56755H/p1709565734801799
Built successfully three times on Tugboat. Spot checked pages.

VACMS-17335: Stabilize build

---

.github/workflows/mirror-images.yml
.github/workflows/production-tag.yml

Relates to #[18683](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18683). 
This simply creates a new tag and uploads it as an artifact so that can be referenced by other workflows.

VACMS-16863: Create and upload an artifact with the tag value.

---

.github/workflows/mirror-images.yml

Relates to #[16863](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16863).
Modifications to workflow. Merge required to test.

Vacms 16863 create image from tag

---

.github/workflows/mirror-images.yml
tag.txt

Relates to #[16863](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16863). 
Need to use `cat` to get the contents of a file.

VACMS-16863: create image from tag

---

src/templates/components/rateYourExperience/index.test.tsx
src/templates/components/rateYourExperience/index.tsx
src/templates/components/rateYourExperience/rateYourExperience.stories.ts
src/templates/layouts/resourcesSupport/index.tsx

Closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17226
- Implements the `RateYourExperience` component
- Adds the component to the Resources and Support template

VACMS-17226: Implements `RateYourExperience` component

---

src/data/queries/index.ts
src/data/queries/numberCallout.ts
src/data/queries/tests/__snapshots__/numberCallout.test.tsx.snap
src/data/queries/tests/numberCallout.test.tsx
src/lib/constants/resourceTypes.ts
src/mocks/numberCallout.mock.js
src/templates/components/numberCallout/index.test.tsx
src/templates/components/numberCallout/index.tsx
src/templates/components/numberCallout/numberCallout.stories.ts
src/templates/components/paragraph/index.tsx
src/types/drupal/paragraph.ts
src/types/formatted/numberCallout.ts

Relates to [14372](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14372)
Local testing
Verify component renders as expected on tugboat.
```[tasklist]
```

14372 number callout

---

.github/workflows/content-release.yml
.github/workflows/playwright.yml
.github/workflows/preview.yml

Relates to: 
https://dsva.slack.com/archives/C01SR56755H/p1711379483449809
https://dsva.slack.com/archives/C04CYC4LMU6/p1711382453727949
```[tasklist]
```

swap public image for ecr image

---

.github/workflows/preview.yml

CI preview check was silently failing even though the check would report a green status.. 
```
Run yarn build:preview
...
Creating an optimized production build ...
✓ Compiled successfully
Collecting page data ...
Generating static pages (0/3) ...
Failed request (Attempt 1 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/oauth/token
Failed request (Attempt 2 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/oauth/token
Failed request (Attempt 3 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/oauth/token
Failed request (Attempt 4 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/oauth/token
Failed request (Attempt [5](https://github.com/department-of-veterans-affairs/next-build/actions …
```

add preview auth secrets to the preview ci check

---

next.config.js
src/data/queries/contactInfo.ts
src/data/queries/tests/__snapshots__/contactInfo.test.tsx.snap
src/data/queries/tests/__snapshots__/resourcesSupport.test.tsx.snap
src/templates/layouts/event/index.test.tsx

- fixes broken builds if `entity.field_benefit_hub_contacts` doesn't exist in the contact info of a resources & support node
- fixes the missing src spam in event tests
- updates snapshots for above^
- reruns yarn to ensure all deps are up-to-date
- bumps largepagebytesize warning up a bit to reduce spam in tugboat
```[tasklist]
```

Resources support pre render, small test fixes

---

jest.config.js

Relates to #[17631](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17631). (or closes?)
Bumped up coverage to 95% and verified that coverage test failed. ran again at 80 and verified that they worked
Verify tests run and pass in pipeline
```[tasklist]
```

updated test coverage thresholds

---

.github/workflows/fetch-latest-release/index.js
generator-templates/component/playwright.hbs
scripts/github-actions/validate-build-status.js

Relates to #498  #502 . I fixed the one github action import but not the second 🤦 I also updated the generator template to use the correct import style for playwright.
I missed these because none of these were used in actual CI checks.... and the plopfile was updated to run correctly, but i forgot to check the templates. sorry for the extra noise!
```[tasklist]
```

One more require

---

READMEs/testing.md
playwright.config.ts
playwright/tests/404page.spec.ts
playwright/tests/a11y.spec.ts
playwright/tests/event.spec.ts
playwright/tests/eventListing.spec.ts
playwright/tests/newsStory.spec.ts
playwright/tests/storyListing.spec.ts
playwright/tests/vetCenter.spec.ts
tsconfig.json

Closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17586

VACMS-17586: Ports Playwright tests to TypeScript

---

src/templates/common/util/HTMLComment.test.tsx
src/templates/components/processList/index.test.tsx
src/templates/components/qaParagraph/index.test.tsx
src/templates/components/servicesList/index.test.tsx
src/templates/components/wysiwyg/index.test.tsx
src/templates/layouts/staffProfile/dataService.test.tsx
src/templates/layouts/wrapper/index.test.tsx

Our branch test coverage across the repo was very close tot he 80% threshold, this adds a few more tests improve that
Local
Test suite passes as expected

Added tests to improve branch coverage

---

.github/workflows/content-release.yml

Relates to issue #18046.
Verified updated GitHub action runs without issue and produces expected results.
```[tasklist]
```

Jbolling issue 18046

---

.github/workflows/content-release.yml
.github/workflows/release-on-push.yml

add job to run content-release every day

---

.github/workflows/content-release.yml
next.config.js
src/templates/layouts/vetCenter/index.tsx

fix issue with certian pages that caused nextbuild to destroy artifacts. Also fix some logging changes that I made earlier

Fix: fix nextjs builds

---

READMEs/templates.md

Updates template.md to contain a list of completed layouts
N/A

Added test links for current templates

---

envs/.env.staging

This pr fixes the drupal base url and image domain for the staging environment.

feat: fix staging URL

---

.github/workflows/gha-metrics-datadog.yml

This sends Github Action stats into Datadog on an ongoing basis, so that we monitor timing and problems with them.
Similar actions run in va.gov-cms and content-build already:
https://github.com/department-of-veterans-affairs/va.gov-cms/actions/workflows/actions-metrics.yml
https://github.com/department-of-veterans-affairs/content-build/actions/workflows/gha-metrics.yml
These metrics can be leveraged in Datadog: https://vagov.ddog-gov.com/notebook/8058/scratchpad-content-release-step-metrics?range=604800000&start=1724809922324&live=true
```[tasklist]
```
GHA does not provide a usable way of testing a workflow that has not been merged to main. 
After merge, a metrics explorer query like this should begin to show data for next-build: …

Adds action to send GHA stats to Datadog.

---

.github/workflows/content-release-staging.yml

Just renames the human label of staging content release to be correct.

Correct human label of staging content release.

---

docker-run.sh
packages/env-loader/src/cms-feature-flags.ts
packages/env-loader/src/env-file.ts

Tcosgrove debug prod env vars

---

docker-run.sh
envs/.env.dev
envs/.env.prod
envs/.env.staging
packages/env-loader/src/env-file.ts

All this does is remove the debug code that we had added and also removing the hard-coded feature flags from the dev staging and prod environments.
This work is captured in #763

Roll out debug code and remove feature flags from env files.

---

.github/workflows/content-release.yml
next-sitemap.config.js

```[tasklist]
```
Before:
After:
```[tasklist]
```
When merging a layout, you must ensure that the content type has been turned on for `next-build` inside the `CMS`. This CMS flag must be turned on for editors to preview their work using the …

feat: redo combined sitemap for new process

---

src/templates/components/personProfile/index.tsx
src/templates/components/wysiwyg/index.tsx
src/templates/layouts/event/index.tsx
src/templates/layouts/eventListing/index.tsx
src/templates/layouts/newsStory/index.tsx
src/templates/layouts/pressReleaseListing/index.tsx
src/templates/layouts/storyListing/index.tsx
src/templates/layouts/vetCenter/index.tsx

Remove unused style classes following content-build's removal of unused classes
Relates to #[767](https://github.com/department-of-veterans-affairs/next-build/issues/767). (or closes?)
```[tasklist]
```
Pages to examine 
```[tasklist]
```
When merging a layout, you must ensure that the content type has been turned on for `next-build` inside the `CMS`. This CMS flag must be turned on for editors to preview their work using the next build preview server.
Resource types (layouts) that have not been approved by design should NOT be pushed to production. Ensure that [slug.tsx](../src/pages/[[...slug]].tsx) does not include your resource type if it …

PR: remove unused styles

---

.github/workflows/content-release.yml

Fix deviaton in how successive if statements work in bash locally vs how they work in GHA runner
```[tasklist]
```
Before:
After:
```[tasklist]
```
When merging a layout, you must ensure that the content type has been turned on for `next-build` inside the `CMS`. This CMS flag must be turned on for editors to preview their work using the next build preview server.
Resource types (layouts) that …

fix: fix issue with formatting differences between GHA run and local linux

---

.github/workflows/content-release.yml

```[tasklist]
```
Before:
After:
```[tasklist]
```
When merging a layout, you must ensure that the content type has been turned on for `next-build` inside the `CMS`. This CMS flag must be turned on for editors to preview their work using the …

Fix Vagov nb sitemap nullcheck

---

envs/.env.dev

Adds the feature flags for events & listings to dev so that they always build.

Add the dev env vars.

---

src/templates/layouts/event/index.tsx

This PR brings parity between content-build and next-build by removing the show all times button from the page after the user has already clicked it.
N/A
```[tasklist]
```
Go to localhost:3000/chicago-health-care/events/53791/
Scroll down to View other times for this event, click it.
Scroll down to the Show all times button, click it.
The show all times button should be removed from that page.
Before:
After:
```[tasklist]
``` …

Removed show all times after it is clicked

---

src/assets/styles/globals.css

Fixes the width of the search bar button and its styling. 
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19410
```[tasklist]
```
Open any page on Tugboat, switch to a mobile viewing width, and open the search bar (click on 'Menu' in the top bar). Example page: https://pr790-kwxsbtuohvekbxewpa4myvpdxxhfx3vd.tugboat.vfs.va.gov/outreach-and-events/events/
Before:
After:
```[tasklist]
```

Add search button styles to global stylesheet.

---

src/pages/_document.tsx

`#announcement-root` is present in content-build template but not in next build. This div serves as the container/root element for the "Announcements" component used by `vets-website`: [source](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/site-wide/announcements/index.jsx).
This is a one-line change, adding the empty div to next-build.
Relates to #[19694](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19694). 
```[tasklist]
```
What needs to be checked to prove this works?  View document source, note the presence of the new div
Before:
After:
- …

#19694: add missing `announcement-root` div

---

additional.d.ts
src/data/queries/supportServices.ts
src/data/queries/tests/__snapshots__/contactInfo.test.tsx.snap
src/data/queries/tests/__snapshots__/resourcesSupport.test.tsx.snap
src/data/queries/tests/supportServices.test.tsx
src/templates/components/contactInfo/contactInfo.stories.ts
src/templates/components/contactInfo/index.test.tsx
src/templates/components/contactInfo/index.tsx
src/templates/layouts/resourcesSupport/index.test.tsx
src/types/formatted/contactInfo.ts

Updates contact info component to align visually with with what is in production. Updates the names of the properties to make a bit more sense with the structure of the data that's being returned from Drupal.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19386
```[tasklist]
```
This component is used on Resources & Support templates but since there aren't any live yet, it can be tested through storybook.
Storybook for contact info:
| Before | After |
| --- | --- |
| <img width="1036" alt="Screenshot 2024-11-25 at 2 16 47 PM" src="https://github.com/user-attachments/assets/5c8363e4-9107-4a18-b73a-e926077e14fa"> |<img width="1039" alt="Screenshot 2024-11-25 at 2 14 33 PM" src="https://github.com/user-attachments/assets/44ffdd21-48ed-4f35-9af1-a0a0df1fa20c"> |
| <img …

VACMS-19386 Update contact info component

---

envs/.env.prod

This removes prod flag overrides for events that were in place earlier for testing purposes.

Remove prod flags.

---

src/templates/common/meta/index.tsx

PR adds a conditional check for the `og:title` property and uses that value for the title tag for events
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19698
```[tasklist]
```
Tested against the local build of a single event and against the outreach and event listing page
Single Event: `/outreach-and-events/events/64661/`
Event Listings: `/outreach-and-events/events/`
Before:
After: 
```[tasklist]
```
When …

VACMS-19698: Updates to event title tag for browser tabs

---

src/templates/common/meta/index.tsx

Reverts department-of-veterans-affairs/next-build#838

Revert "VACMS-19698: Updates to event title tag for browser tabs"

---

src/lib/utils/medallia.test.ts
src/lib/utils/medallia.ts
src/templates/common/contentFooter/index.tsx

Updates the Medallia Feedback button logic to match what is currently in production/content-build.
❗ Medallia surveys are not able to be tested locally / in dev. It can only be tested completely in staging and production.
```[tasklist]
```
Before:
After:
```[tasklist]
```
When merging a layout, you must ensure that the content type has been turned on for `next-build` inside the `CMS`. This CMS …

Update Medallia logic to what is in production

---

envs/.env.example

It uncomments `FEATURE_NEXT_BUILD_CONTENT_ALL` in `env.example` such that when we copy from it to `env.local` more pages can be loaded for ease of local development. 
No ticket
NA  See[ slack thread](https://dsva.slack.com/archives/C01SR56755H/p1739471871869769) 
```[tasklist]
```
N/A
What needs to be checked to prove this works?  N/A
What needs to be checked to prove it didn't break any related things?  N/A
What variations of circumstances (users, actions, values) need to be checked? N/A
Before:
After:
N/A 
```[tasklist]
```
When merging a layout, you must ensure that the content type …

Uncommenting FEATURE_NEXT_BUILD_CONTENT_ALL flag in env.example

---

src/templates/common/banners/banner/index.test.tsx
src/templates/common/banners/banner/index.tsx
src/templates/common/banners/facilityBanner/index.test.tsx
src/templates/common/banners/facilityBanner/index.tsx
src/templates/common/banners/maintenanceBanner/index.test.tsx
src/templates/common/banners/maintenanceBanner/index.tsx
src/templates/common/banners/promoBanner/index.test.tsx
src/templates/common/banners/promoBanner/index.tsx

Removes `role="region"` from banners and removes `aria-label` from Maintenance Banner. Also updates related tests
Closes to #[20161](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20161).
```[tasklist]
```
- See the above testing steps
- View banners in story book
- N/A
```[tasklist]
```
When merging a layout, you must ensure that the content type has been turned on for `next-build` inside the `CMS`. This CMS flag must be turned on for editors to preview their work using the …

Vacms 20161 aria fixes

---

src/templates/common/googleMapsDirections/index.test.tsx
src/templates/common/googleMapsDirections/index.tsx
src/templates/layouts/event/index.tsx
src/templates/layouts/vetCenter/index.tsx

Removes un-needed space on location link and adds an aria-label to google maps link when there is a location name available. Updates the props for the <GoogleMapsDirections> component. Removes un-used `title` prop and adds `location`. As a result vet-center pages are now also showing an aria-label for these links.
Closes to #[19689](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19689).
Closes to #[19674](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19674).
```[tasklist]
```
```[tasklist]
```
When merging a layout, you must ensure that the content type has been turned on for `next-build` inside the `CMS`. This …

VACMS-19689 -9674 location updates

---

packages/proxy-fetcher/src/index.ts
src/pages/[[...slug]].tsx

Adds logging to help us debug when pages 404.

Add some more explicit logs

---

src/templates/layouts/pressRelease/index.test.tsx
src/templates/layouts/pressRelease/index.tsx

Several bugs around the links at the bottom of the press release page.
Closes #[20169](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20169).
& 
Closes #[20165](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20165)

VACMS 20169 press release bugs

---

.github/pull_request_template.md

Minor update to the PR template, adjusting the slack channel to post over to the latest name
This pull request includes a small change to the `.github/pull_request_template.md` file. The change updates the Slack channel to be alerted for PR reviews from `#accelerated-publishing` to `#next-build`.
* [`.github/pull_request_template.md`](diffhunk://#diff-b2496e80299b8c3150b1944450bd81c622e04e13d15c411d291db0927d75fd6bL25-R25): Changed the Slack channel for PR review alerts to `#next-build`.
No related ticket
```md
```
No testing here, just template update for github
No QA required
Before:
After:
No
---
```md
```
When merging a layout, you must ensure that the content type has been turned on …

Update github PR template to adjust slack channel for updated #next-build

---

src/templates/layouts/healthCareLocalFacility/index.tsx

@laflannery's [comment on my last PR](https://github.com/department-of-veterans-affairs/next-build/pull/923#issuecomment-2715375837).

Clean up some unnecessary classes

---

src/templates/layouts/healthCareLocalFacility/index.tsx

Very minor PR that fixes a CI step failure.

Very minor format fix on healthCareLocalFacility.

---

src/data/queries/index.ts
src/data/queries/vetCenterOutstation.ts
src/lib/constants/resourceTypes.ts
src/mocks/vetCenterOutstation.mock.tsx
src/templates/components/imageAndStaticMap/index.tsx
src/templates/layouts/vetCenterOutstation/index.test.tsx
src/templates/layouts/vetCenterOutstation/index.tsx
src/templates/layouts/vetCenterOutstation/vetCenterOutstation.stories.ts
src/types/formatted/vetCenterOutstation.ts

Adds Vet Center Outstations to next-build for further development. The VC Outstation is fully available as a layout in Storybook [here](https://storybook-su8opn6wxobyeenm0peyj6wpqplwtrdq.tugboat.vfs.va.gov/?path=/docs/layouts-vetcenteroutstation--docs).
This pull request introduces support for the new `VetCenterOutstation` resource type. The changes include adding the necessary imports, constants, query implementations, and mock data to handle this new resource type.
* [`src/data/queries/index.ts`](diffhunk://#diff-4736203072bd77be64e5041b8727a153d8cb72e7ffec7c999324edb7a43c44d2R49): Added `VetCenterOutstation` to the list of imports and the `QUERIES_MAP` to support the new resource type. [[1]](diffhunk://#diff-4736203072bd77be64e5041b8727a153d8cb72e7ffec7c999324edb7a43c44d2R49) …

[VACMS-20706]Vet Center Outstations

---

scripts/logNextBuildNetworkFailures.cjs

This PR adds a script to parse through logs, uses Github API and takes in date and max page as a parameter to print to console and generate a CSV.
N/A - I don't have copilot yet :(
Closes 20815 (https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20815)
```md
```
Just ran the script node logNextBuildNetworkFailures.cjs 2025-03-25 2025-03-28 1
NA
What needs to be checked to prove this works?
What needs to be checked to prove it didn't break any related things?
NA
---
```md
```
When merging a …

Adding a script to parse content release logs

---

src/templates/layouts/newsStory/index.test.tsx
src/templates/layouts/newsStory/index.tsx

This PR ensures that the date in the story details page uses a semantic tag and adds a test.
This pull request updates the `NewsStory` component to improve semantic HTML by wrapping the `time` element in a `<p>` tag and adds a corresponding test to ensure this behavior is correctly implemented.
* [`src/templates/layouts/newsStory/index.tsx`](diffhunk://#diff-16d8e739d5a51a8ab3dfdbdea3d9a7f9eda7c2386699aa52720b85d487f32ebfL55-R57): Replaced the `<div>` wrapping the `time` element with a `<p>` tag to improve semantic HTML structure.
* [`src/templates/layouts/newsStory/index.test.tsx`](diffhunk://#diff-1620ae9453fcfad5678994d536122e0117c86461afe86d5f0d158ec513888761R132-R139): Added a test to verify that the `time` element is rendered within a `<p>` tag and displays the correct date.
Closes …

VACMS: 20807 - Story Details using semantic tag

---

src/data/queries/healthCareLocalFacility.ts
src/data/queries/tests/__snapshots__/healthCareLocalFacility.test.tsx.snap
src/data/queries/tests/healthCareLocalFacility.test.tsx
src/data/queries/tests/storyListing.test.tsx
src/mocks/healthCareLocalFacility.mock.json
src/templates/common/relatedLinks/index.tsx
src/templates/layouts/healthCareLocalFacility/index.test.tsx
src/templates/layouts/healthCareLocalFacility/index.tsx
src/types/drupal/node.ts
src/types/drupal/paragraph.ts
src/types/formatted/healthCareLocalFacility.ts

Adds the related links section. It was probably more painful than it needed to be because of the stuff that was in there already but unused. Leveraging the existing component and incorrect static types...I had to fix some stuff along the way.
**Note:** The DOM is different. @laflannery The `<ul>` -> `<li>` -> `<p>` -> `<va-link>` was what was already in this component in Next Build. Should I continue to use that? I was thinking yes because of the increased font size thing. Also using an unordered list seemed better than a div, but please sanity check me on that. 😅 
Increased font size:
This pull request introduces updates to the `HealthCareLocalFacility` query, enhancing its functionality to include related links, updating snapshots for testing, and refining data formatting. Key changes …

VAMC facility related links

---

src/assets/styles/globals.css

This PR adds a missing CSS property for the mobile search button. I dug around to try to figure out why the style sheet doesn't get loaded with the app, but didn't figure that out. I did see that we already added styles locally, so I just updated that.
This pull request makes a small adjustment to the global CSS styles by adding a `padding: 0` rule to the `body` element in `globals.css`.
Closes [20158](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20158)

VACMS-20158: Mobile search button padding

---

src/lib/utils/capitalizeWords.test.ts
src/lib/utils/capitalizeWords.ts
src/templates/common/meta/index.tsx

Created a utility to capitalize the first letter of each word in a string. Used the utility to capitalize each word in the meta Title.
This pull request introduces a new utility function, `capitalizeWords`, to capitalize the first letter of each word in a string, along with its integration and corresponding tests. The changes enhance code reusability and improve the formatting of meta tag titles.
* [`src/lib/utils/capitalizeWords.ts`](diffhunk://#diff-2178749086ef85dc833ec157a92d1766088e39cf3114c578faa9496bafd79734R1-R11): Added the `capitalizeWords` function, which transforms a string so that each word starts with an uppercase letter.
* [`src/lib/utils/capitalizeWords.test.ts`](diffhunk://#diff-e44408eba681a6dedf2ac90daa91dfbd2752719ba831c0726ad9d86d92a25b27R1-R18): Added unit tests for …

VACMS-20188: meta Title Capitalization

---

src/data/queries/healthCareLocalFacility.ts
src/data/queries/tests/__snapshots__/healthCareLocalFacility.test.tsx.snap
src/data/queries/wysiwyg.ts
src/lib/utils/getHtmlFromField.ts
src/lib/utils/hashReference.test.ts
src/lib/utils/hashReference.ts
src/mocks/healthCareLocalFacility.mock.json
src/templates/layouts/healthCareLocalFacility/LocationServices.test.tsx
src/templates/layouts/healthCareLocalFacility/LocationServices.tsx
src/templates/layouts/healthCareLocalFacility/index.test.tsx
src/templates/layouts/healthCareLocalFacility/index.tsx
src/types/drupal/node.ts
src/types/formatted/healthCareLocalFacility.ts

Adds the "Prepare for your visit" section.
This pull request enhances the `HealthCareLocalFacility` query and its associated components by adding support for "Location Services" data, improving data processing, and updating tests and mocks accordingly. Key changes include adding a new utility function for HTML processing, modifying the query to include location services, and implementing a new `LocationServices` component with tests.
* Added `field_location_services` to the query parameters and updated the formatter to process and map location services data, including titles and WYSIWYG content (`src/data/queries/healthCareLocalFacility.ts`). [[1]](diffhunk://#diff-35c09c75baec6b07a198e9d78d40d7db3a47ac9fc1c9a1e68a3566c1faf7303fR27) …

VAMC facility: Prepare for your visit

---

.eslintrc.json
scripts/dependency-tree-visualizer/DependencyGraph.ts
scripts/dependency-tree-visualizer/README.md
scripts/dependency-tree-visualizer/analyzeLiquid.ts
scripts/dependency-tree-visualizer/colorizePath.ts
scripts/dependency-tree-visualizer/emitConsoleTree.ts
scripts/dependency-tree-visualizer/emitDotGraph.ts
scripts/dependency-tree-visualizer/findDependencies.ts
scripts/dependency-tree-visualizer/index.ts
scripts/dependency-tree-visualizer/tsconfig.json

This tool allows us to visualize the dependency tree for any given template. This can emit both to console and `.dot` file. If we find it useful later, we can also create a JSON emitter for consumption by some other tool.
I wrote this in TypeScript (because I like static types 🤷), so we'll need to either use `ts-node`, `bun`, or `deno` to run it.
**Example 1:** Emit to console
```sh
bun scripts/dependency-tree-visualizer/index.ts ../content-build/src/site/layouts/health_care_local_facility.drupal.liquid
```
**Example 2:** Emit to `.dot` file
Use the `--dot` flag:
```sh
bun scripts/dependency-tree-visualizer/index.ts ../content-build/src/site/layouts/health_care_local_facility.drupal.liquid --dot && dot -Tsvg graph.dot -o graph.svg
```
> [!important]
> To generate the graph from the `.dot` …

Dependency tree visualizer

---

src/templates/layouts/pressReleaseListing/index.tsx

This PR performs v1-v3 grid migration on news listing pages.
This pull request updates the layout and grid structure in the `PressReleaseListing` component to align with the `vads-grid` system, improving consistency with the design system used across the project.
* Replaced `usa-grid` and `usa-grid-full` classes with `vads-grid-container` to standardize the grid container. (`[src/templates/layouts/pressReleaseListing/index.tsxL61-R76](diffhunk://#diff-42527bcb586149f1fd274f8c4283e73cee9b493c8fcccd37b50a012497c91e1bL61-R76)`)
* Updated the inner layout by replacing `usa-width-three-fourths` with a combination of `vads-grid-row` and `vads-grid-col-9`, ensuring better alignment with the `vads-grid` system. (`[src/templates/layouts/pressReleaseListing/index.tsxL61-R76](diffhunk://#diff-42527bc …

News listing page Grid migration

---

src/data/queries/tests/__snapshots__/vamcSystemVaPolice.test.tsx.snap
src/data/queries/vamcSystemVaPolice.ts
src/templates/layouts/vamcSystemVaPolice/index.test.tsx
src/templates/layouts/vamcSystemVaPolice/index.tsx
src/types/drupal/node.ts
src/types/formatted/vamcSystemVaPolice.ts

(Select this text, hit the Copilot button, and select "Generate".)
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20852
Closes _link to ticket_
```md
```
Check the following VAMC System VA Police pages:
- [VA Alaska health care VA Police](https://pr1060-yx9wtckpf6zxjdphsc66gbgvew25sgoj.tugboat.vfs.va.gov/alaska-health-care/va-police/)
- [VA Eastern Colorado health care VA Police](https://pr1060-yx9wtckpf6zxjdphsc66gbgvew25sgoj.tugboat.vfs.va.gov/eastern-colorado-health-care/va-police/)
- [VA Spokane health care VA Police](https://pr1060-yx9wtckpf6zxjdphsc66gbgvew25sgoj.tugboat.vfs.va.gov/spokane-health-care/va-police/)
---
This section lists items that need to be checked or updated when making changes to …

VACMS-20852: Shows Police Intro

---

src/lib/drupal/staffProfileSideNav.ts

Fixes inverted replace, that was switch `"` to `&quot;`
This pull request updates the `buildStaffProfileSidebarData` function in `src/lib/drupal/staffProfileSideNav.ts` to fix the handling of double quotes in titles.
Key change:
* Updated the `formattedTitle` logic to replace `&quot;` with `""` instead of replacing `"` with `&quot;`, ensuring proper formatting of double quotes in the title.
Closes [21463](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/21463)
Before:
After:
---

VACMS-21463: quote fix

---

next-sitemap.config.js

Removes changefreq and priority from next build sitemap.
This pull request updates the `next-sitemap.config.js` file to enhance sitemap configuration options by adding new properties for customization.
* [`next-sitemap.config.js`](diffhunk://#diff-8c4981164a106326e9988c8aa5267160938ea7950f33eac3d53ef206deb31e06R13-R14): Added `changefreq` and `priority` properties to the sitemap configuration, allowing for more granular control over sitemap entries. Both properties are set to `false` by default.
Closes [21434](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/21434)
---

remove changefreq and priority from sitemap.

---

src/templates/common/relatedLinks/index.tsx

Closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/21303

Add ID to related links h2

---

.github/workflows/content-release.yml

We are changing the sitemap name in content-build. This change picks up that rename.
To be merged after https://github.com/department-of-veterans-affairs/content-build/pull/2560
This pull request updates the sitemap URLs in the `.github/workflows/content-release.yml` file to use a new naming convention for the `CB_SITEMAP_LOCATION` variable.
Workflow updates:
* Updated the `CB_SITEMAP_LOCATION` variable for all build types (`dev`, `staging`, `prod`, and default) to point to the `sitemap-cb.xml` file instead of the previous `sitemap.xml` file. This ensures consistency with the new sitemap naming convention.
Relates to  [21435](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/21435)
---
This section lists items that need to be checked or updated when making changes to …

pickup sitemap rename from content-build

---

src/templates/layouts/vamcSystemVaPolice/index.tsx

This changes the grid used on the VAMC System VA Police page from the USWDS v1 to the v3.
This pull request updates the layout structure and CSS classes in the `VamcSystemVaPolice` component to align with the design system's grid framework and improve consistency across the application.
Changes to layout structure and CSS classes:
* [`src/templates/layouts/vamcSystemVaPolice/index.tsx`](diffhunk://#diff-7f60f2fbb2a58f412c3be4aeb9b837d4f77410652270f2e6274863f13fa84d0fL32-R37): Replaced `usa-grid` and `usa-width-three-fourths` classes with `vads-grid-container`, `vads-grid-row`, and `vads-grid-col-12` classes to conform to the design system's grid framework.
* [`src/templates/layouts/vamcSystemVaPolice/index.tsx`](diffhunk://#diff-7f60f2fbb2a58f412c3be4aeb9b837d4f77410652270f2e6274863f13fa84 …

VACMS-21213: Changes grid container

---

src/data/queries/locationsListing.ts
src/data/queries/tests/__snapshots__/locationsListing.test.tsx.snap
src/data/queries/tests/locationsListing.test.tsx
src/templates/layouts/locationsListing/index.test.tsx
src/templates/layouts/locationsListing/index.tsx
src/types/formatted/locationsListing.ts

Adds the main facilities section data to the locations listing page.
This pull request enhances the functionality of the `LocationsListing` feature by integrating support for "Main Facilities." It introduces new data fetching logic, updates data formatting, modifies the layout to display facilities, and adds comprehensive tests to ensure proper functionality.
* [`src/data/queries/locationsListing.ts`](diffhunk://#diff-bd9fa099a45ae5efad2771d3be89c3ca5c4bd2b41099034ee69ca2e92275f76fL53-R77): Added logic to fetch and sort "Main Facilities" related to a `LocationsListing` entity using `fetchAndConcatAllResourceCollectionPages`. Integrated the fetched data into the `data` return object.
* [`src/data/queries/locationsListing.ts`](diffhunk://#diff-bd9fa099a45ae5efad2771d3be89c3ca5c4bd2b41099034e …

Locations Listing - Main Facilities

---

src/templates/layouts/locationsListing/index.test.tsx
src/templates/layouts/locationsListing/index.tsx

Adding common footer and a test
This pull request introduces a new feature to the `LocationsListing` component by replacing a placeholder with the `ContentFooter` component and adding a corresponding test to ensure its presence. The changes improve the user interface and maintain test coverage.
* [`src/templates/layouts/locationsListing/index.tsx`](diffhunk://#diff-e12ae8c4376cbdb26e3000d6f3d647ea54237c8b2cadd37ef2943e874836998fR6): Replaced the placeholder `<div>TODO: Above-footer elements</div>` with the `ContentFooter` component to enhance the layout of the `LocationsListing` page. Added an import statement for `ContentFooter`. [[1]](diffhunk://#diff-e12ae8c4376cbdb26e3000d6f3d647ea54237c8b2cadd37ef2943e874836998fR6) [[2]](diffhunk://#diff-e12ae8c4376cbdb26e3000d6f3d647ea54237c8b2cadd37 …

Locations Listing - Footer

---

src/templates/layouts/vetCenter/index.tsx

Perform small content fixes on "Main location" section. See ticket for a checklist.
Closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/21559
Before:
After:

Vets Center: Perform small content fixes on "Main location" section

---

docs/template-migration/guide-to-leveraging-ai.md
docs/template-migration/phases/active-migration/readme.md

A quick and dirty guide for leveraging AI for template migration. It's hardly magic, but it's good to write down for posterity.
Closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/21192

Guide to leveraging AI for template migration

---

packages/env-loader/src/cli-options.ts
src/data/queries/tests/__snapshots__/vbaFacility.test.tsx.snap
src/data/queries/vbaFacility.ts
src/pages/[[...slug]].tsx
src/templates/layouts/vbaFacility/index.test.tsx
src/templates/layouts/vbaFacility/index.tsx
src/types/drupal/node.ts
src/types/formatted/vbaFacility.ts

Adds the CC intro text and fixes issue with Commander update.
Closes [21628](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/21628)
---

VAMC-21628: cc intro text

---

.github/workflows/ci.yml

Separating out CI jobs and adding playwright as CI job so we can add them as branch protections. 
Closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/21732
```md
```
What needs to be checked to prove this works?
What needs to be checked to prove it didn't break any related things?
Before:
After:
---

VACMS-21732: have playwright tests action be required before a deploy to production

---

.github/workflows/ci.yml

Closes _link to ticket_
```md
```
What needs to be checked to prove this works?
What needs to be checked to prove it didn't break any related things?
Before:
After:
---
```md
```
When merging a layout, you must ensure that the content type has been turned on for `next-build` in the [.tugboat.env](../envs/.tugboat.env). This method mocks the CMS flag that must be turned on for a layout to be included in the build.
The layout component and matching resource type should be included in the …

remove playwright from ci workflow

---

src/data/queries/tests/__snapshots__/vbaFacility.test.tsx.snap
src/data/queries/vbaFacility.ts
src/templates/layouts/vbaFacility/index.test.tsx
src/templates/layouts/vbaFacility/index.tsx
src/types/formatted/vbaFacility.ts

Adds "Can't find the service you're looking for?" alert from CC data.
This pull request introduces a new "Can't find benefits" alert feature to the `VbaFacility` component. The changes include updates to the data model, formatter logic, component rendering, and associated tests to support this new functionality.
* **Data Model Update**:
- Added a new `CantFindBenefits` type and integrated it into the `VbaFacility` type to represent the alert's header, description, and link details. (`src/types/formatted/vbaFacility.ts`) [[1]](diffhunk://#diff-9cfa14a603217bff452d03c9ff41e25172b973d602b74e05d2df5f8bd671f802R10-R18) [[2]](diffhunk://#diff-9cfa14a603217bff452d03c9ff41e25172b973d602b74e05d2df5f8bd671f802R32)
* **Formatter Logic**:
- Updated the `formatter` in `vbaFacility.ts` to map the new …

VACMS-21634: cant find benefits alert.

---

src/templates/layouts/vetCenterLocationListing/index.tsx

- Simplified the wrapper structure like we did for the main vets page (view diff without whitespace)
- Translated remaining v3 classes
Closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/21646
Test a few pages at various breakpoints:
- http://localhost:3999/fargo-vet-center/locations/
- http://localhost:3999/colorado-springs-vet-center/locations/
- http://localhost:3999/st-paul-vet-center/locations/

Vet Center Locations: Migrate all pre-v3 classes

---

src/components/banner/template.test.tsx
src/components/banner/template.tsx
src/components/vbaFacility/__snapshots__/query.test.ts.snap
src/components/vbaFacility/formatted-type.ts
src/components/vbaFacility/mock.json
src/components/vbaFacility/query.ts
src/pages/[[...slug]].tsx
src/types/drupal/node.ts

Adds the banner from VBA page content if it exists. This functionality can be used by any resource that has a banner property and value.
This pull request introduces a new facility banner feature for VBA Facility pages, allowing for configurable alert banners to be displayed with customizable content and options. The changes include updates to type definitions, mock data, formatting logic, and page rendering to support this feature.
**Facility Banner Feature**
* Added a new `VbaBanner` type and integrated it into the `VbaFacility` type to support banner configuration, including display status, alert type, title, body, and dismiss options. [[1]](diffhunk://#diff-f5cac2c5a094a7af606b373a63db933dbbbcfdc50808def5dbd114a816d0860bR24-R30) …

VACMS-22113: vba banner

---

src/pages/_playground/api-explorer.tsx

I was getting tired of having to re-enter my filters when exploring the API data. I also wanted to be able to share what I was seeing with teammates. Now you can copy the URL and share it.
Before:
After:

API Explorer: Save the queries to the url query string for sharing and persistence

---

README.md

This pull request makes a minor update to the setup instructions in the `README.md` file. The change simplifies the Node version management step by removing the explicit version requirement.
Just doing some housekeeping.

Update README.md nvm Basic Installation

---

next.config.js

Removed extra experimental and also removed instrumental since it is enabled by default now in nextjs

remove extra experimental - instrumental not needed

---

envs/.env.tugboat
next.config.js

Increases timeout and exclude babel logs in tugboat builds
Relates to [22166](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/22166)
---

extend timeout and remove babel from tugboat log.

---

src/components/button/__snapshots__/query.test.ts.snap
src/components/button/query.ts
src/components/resourcesSupport/__snapshots__/query.test.ts.snap

Fixes the bad local spotlight links. Note that this _doesn't_ address the national spotlight links. That'll be taken care of from within Drupal, I believe.
Closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/22164

Prefer the URL if it exists
