src/components/paragraph/audience_topics/index.tsx, src/pages/demo/audienceTopics/index.tsx, src/utils/utils.ts
Audience Topics with sorting filter to match current behavior
Ticket: `https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8609`
Existing Component: `https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/includes/tags.drupal.liquid`
Notes: The only thing I don't understand about the previous component is it was treated as an include rather than a paragraph. Let me know if I need to move this to a new directory.
=> VACMS-8609-paragraph-audience-topics

src/components/image/index.test.jsx, src/components/image/mediaImageIndividual.json
Focused on testing the Image side of things, since the Media side is actually already covered [here](https://github.com/department-of-veterans-affairs/next-build/blob/main/src/components/media/index.test.tsx).
=> VACMS-9185: Add tests for ImageComponent

additional.d.ts, src/components/footer/index.test.jsx, src/mocks/mockFetch.ts
=> Declare Test Utils Module

src/components/paragraph/index.tsx, src/components/paragraph/rich_text_char_limit_1000/index.test.tsx, src/components/paragraph/rich_text_char_limit_1000/index.tsx, src/pages/demo/richTextCharLimit1000/index.tsx, src/pages/index.tsx, src/types/paragraph.ts
=> VACMS 8639 Component - Paragraph Rich Text Char Limit 1000

src/data/queries/questionAnswer.ts, src/data/queries/tests/__snapshots__/audienceTopic.test.tsx.snap, src/data/queries/tests/__snapshots__/button.test.tsx.snap, src/data/queries/tests/__snapshots__/questionAnswer.test.tsx.snap, src/data/queries/tests/audienceTopic.test.tsx, src/data/queries/tests/button.test.tsx, src/data/queries/tests/questionAnswer.test.tsx, src/mocks/audienceTopics.mock.json, src/mocks/button.mock.json, src/mocks/questionAnswer.mock.json, src/pages/_playground/api-explorer.tsx, src/types/dataTypes/drupal/node.ts
This adds 
* tests that I should have added in #104 and #105
* fixes to formatters exposed by these tests (yay tests!)
* a simple utility page for printing serialized/normalized but otherwise unformatted data from Drupal. I'd like to eventually expand this to something akin to CodePen that would let people browse the resources that come from the Content API, put together queries, see how those queries will be formatted, etc.
=> Add snapshot tests for formatters; add basic serialized json retriever.

src/lib/utils/drupalClient.ts
should fix the problem when building locally using the https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov endpoint. if the codeQL check is okay with it 🤞 
[ ] - does the site resolve correctly locally when using the content build endpoint?
[ ] - when using the local ddev cms endpoint?
[ ] - on tugboat environments?
=> use string.match() instead of array.includes() to check hostname

.tugboat/config.yml
Relates to #138 
sitemap is correctly generated for tugboat envs now
I had to rebuild the pr environment a lot before the command didn't work. something feels flaky on the endpoint when building, the failed slugs are rarely the same from run to run.
before
after
visit https://pr140-pbomutnnzidvsnpkvota2cfpndh290bv.tugboat.vfs.va.gov/sitemap.xml
=> Tugboat sitemaps

src/templates/common/image/index.test.jsx, src/templates/components/newsStoryTeaser/index.test.tsx, src/templates/layouts/newsStory/index.test.tsx
Cleans up console for tests. Mocks console warning and errors in files where they are not needed.
Local
- Verify tests still pass
- Verify that console doesnt have any unnecessary logs when running unit tests
=> mock console errors in jest tests where logs arent needed

.tugboat/config.yml, src/pages/[[...slug]].tsx
Right now, Tugboat builds are consistently failing on random urls. There are 3 main sources of failures:
- "Bad Gateway" 
- "Unexpected < in JSON" coming from the banner endpoint
- "absolute urls are not allowed", sporadic, but almost always a request or two after one of the other errors
I turned off the banner endpoint to eliminate that second source, which eliminates many instances of the third one. The banner endpoint should be turned back on as part of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14779
The "Bad Gateway" error I am still investigating, I think it is related to the response header size but I am not 100% on that yet.
It happens much more sparingly with banners turned off as well, but it still happens 1-2x a run.
=> switch from apache to nginx

.eslintignore, .eslintrc.json, .gitignore, scripts/setup-dev.js, src/pages/[[...slug]].tsx, src/pages/_app.tsx, tsconfig.json
After creating the symlink to vets-website (`yarn dev`), other commands would fail: name `yarn test:types` and `yarn build` or `yarn export` (both of which check types) due to typescript looking at all of the generated files from vets-website. We don't need to be checking those, they aren't ours. And they cause our stuff to break if we do.
```
yarn test:types
<--- Last few GCs --->
[8923:0x148040000]    15316 ms: Scavenge 4041.1 (4113.6) -> 4040.0 (4117.9) MB, 5.5 / 0.0 ms  (average mu = 0.564, current mu = 0.386) allocation failure;
[8923:0x148040000]    15330 ms: Scavenge 4045.1 (4118.1) -> 4043.6 (4136.1) MB, 7.5 / 0.0 ms  (average mu = 0.564, current mu = 0.386) allocation failure;
[8923:0x148040000]    15806 ms: Mark-sweep 4055.6 (4136.1) -> 4051.4 (4151.1) MB, 460.6 / 0.0 ms …
```
=> exclude generated files from typechecking

.eslintrc.json, next.config.js, src/lib/utils/drupalClient.ts, src/lib/utils/staticPaths.ts, src/pages/[[...slug]].tsx
Overcomes previous limit of 2000. The previous limit was made possible by a mechanism provided by next-drupal that overrides the limit of 50. This PR uses the individual page limit of 50, but fetches all pages (in parallel, other than the first, which is fetched before all others to determine the total number of pages to be fetched) and glues them together.
Closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15122
Built on Tugboat. Resources that were previously missing are now present. Built page count increases by ~1000.
The successful build on this PR is really the QA. We can spot check that some pages exist. Notably, this page exists and it doesn't exist on the main build as of this writing (before this PR): …
=> VACMS-15122: Fetches all resources by gluing pages together.

public/importHeaderData.js, src/assets/styles/globals.css, src/data/queries/storyListing.ts, src/lib/utils/helpers.ts, src/templates/globals/banners/promoBanner/index.tsx, src/templates/layouts/storyListing/index.tsx
Relates to #[15063](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15063). (or closes?)
Fixes:
- width in main layout div
- image sizes
- Font size differences
- Incorrect font in teaser text
- truncate function always adding '...' even when not truncating
Note:
- Does not address padding discrepancies in the facility side-nav as we will be switching to using the vets-website side-nav
- The main visual difference is that breadcrumbs are not yet in next-build, this ticket does not address that
Local visual testing
Navigate to story listing page or story page and verify that it looks like the live site 
=> 15063 - CSS and layout fixes for next-build

.tugboat/config.yml, envs/.env.tugboat, scripts/build-vets-website.sh, scripts/install-nvm.sh, scripts/install-repos.sh
Relates to #[#14977](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14977).
We were sourcing the main entry point from the correct place before, but then the bundle looked for local asset paths anyways. So now I am providing those local asset paths on tugboat.
This should unblock #183 to be tested on tugboat, because the asset paths for the side nav widget will able to properly load.
Checked the generated tugboat environment and saw that assets from vets-website were present and available to the build:
Compare with the main preview tugboat environment, which has a ton of additional errors in the browser console:
https://pr184-6ojykrqnalsqywbph3phj1v1lvlufaqq.tugboat.vfs.va.gov/butler-health-care/stories/
```[tasklist]
```
- Add links to …
=> initial stab at building vets-web as part of our tugboat

additional.d.ts, src/data/queries/newsStory.ts, src/data/queries/staticPathResources.ts, src/data/queries/storyListing.ts, src/data/queries/tests/__snapshots__/newsStory.test.tsx.snap, src/lib/drupal/listingPages.test.ts, src/lib/drupal/listingPages.ts, src/lib/drupal/lovell.test.ts, src/lib/drupal/lovell.ts, src/lib/drupal/staticProps.ts, src/lib/utils/slug.test.ts, src/lib/utils/slug.ts, src/mocks/newsStory.mock.json, src/pages/[[...slug]].tsx, src/templates/components/lovellSwitcher/index.tsx, src/templates/components/lovellSwitcher/lovellSwitcher.stories.tsx, src/templates/layouts/newsStory/index.test.tsx, src/templates/layouts/newsStory/index.tsx, src/types/dataTypes/drupal/field_type.d.ts, src/types/dataTypes/drupal/node.ts, src/types/index.d.ts
Relates to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14744
=> VACMS-14744: Lovell switcher and business logic

src/data/queries/headerFooter.ts, src/lib/utils/header.test.ts, src/lib/utils/header.ts, src/lib/utils/headerFooter.test.ts, src/lib/utils/headerFooter.ts
Relates to #183. @ryguyk pointed out how to use addInclude properly, so we don't need to make additional queries for the promo blocks. They correctly come along for the ride with the menu data, which simplifies some of the logic when constructing the data into shape. Nice! 
- visit any story or story listing page, check the megamenu and footer and see that promo blocks are present on sections that have them in the cms (top-level `About VA`, or the `Disability`, `Education` hubs underneath the first item)
```[tasklist]
```
=> clean up header queries

src/lib/drupal/lovell/constants.ts, src/lib/drupal/lovell/staticProps.ts, src/lib/drupal/lovell/tests/utils.test.ts, src/lib/drupal/lovell/utils.ts
Closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15825
- Unit tests added
- QA steps below
- New functionality from this PR:
- Ensure Lovell listing pages have correct breadcrumbs:
- Ensure Lovell bifurcated stories have correct breadcrumbs:
- Existing functionality; ensure still correct:
- Ensure Lovell non-bifurcated stories have correct breadcrumbs:
- Ensure non-Lovell listing pages have correct breadcrumbs:
- Ensure non-Lovell story pages have correct breadcrumbs:
=> Vacms 15825 lovell breadcrumbs

.tugboat/config.yml, .tugboat/vhost-storybook.conf, .tugboat/vhost-web.conf
=> 14711 - 404 page on tugboat

src/assets/styles/globals.css, src/templates/layouts/newsStory/index.tsx, src/templates/layouts/storyListing/index.tsx
Relates to #[15061](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15061). (or closes?)
- Adds feedback button styling
- Puts content footer below article for correct padding
- Adds conditional class for padding below newstory images
- 
Local visual testing
- Navigate to a story listing page (/butler-health-care/stories/)
- Verify layout matches prod
- Navigate to story page
- Verify layout matches prod
=> 15061 Story layout fixes

src/data/queries/newsStory.ts, src/data/queries/storyListing.ts, src/data/queries/tests/__snapshots__/newsStory.test.tsx.snap, src/lib/constants/environment.ts, src/lib/constants/resourceTypes.ts, src/lib/drupal/listingPages.ts, src/lib/drupal/lovell/tests/mockData.ts, src/lib/drupal/lovell/tests/utils.test.ts, src/lib/drupal/staticProps.ts, src/lib/utils/environment.test.ts, src/lib/utils/environment.ts, src/mocks/newsStory.mock.json, src/pages/[[...slug]].tsx, src/templates/common/contentFooter/index.tsx, src/templates/globals/medallia/index.tsx, src/templates/globals/meta/index.tsx, src/templates/layouts/newsStory/index.test.tsx, src/templates/layouts/storyListing/index.test.tsx, src/types/dataTypes/drupal/metatag.ts, src/types/dataTypes/formatted/metatags.ts, src/types/dataTypes/formatted/newsStory.ts, src/types/dataTypes/formatted/path.ts, src/types/dataTypes/formatted/storyListing.ts
Relates to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16105
Custom meta tags were made available via JSON:API in recent work. This PR places those custom meta tags, along with other global meta tags, on the page.
Manual; see QA steps
- Visit a number of different page types and ensure meta tags are in the page markup
=> Vacms 16105 metatags

src/lib/drupal/drupalClient.ts, src/lib/drupal/queryResources.ts
disabling redis cache so cms tugboats don't exit because of a missing service that they shouldn't depend on
```[tasklist]
```
=> Redis hotfix

packages/env-loader/src/cli-options.ts, packages/env-loader/src/index.ts
Relates to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15322
Some small follow-on work to add some additional help text to `--help` commands.
`yarn test -h` should show additional help
```
Additional `test` commands:
Update Snapshots:
$ yarn test:update-snapshots
$ yarn test:u
Usage: test [options]
Options:
--NEXT_IMAGE_DOMAIN <url>             Drupal image domain
--NEXT_PUBLIC_ASSETS_URL <url>        Where to source vets-website assets
--NEXT_PUBLIC_BUILD_TYPE <buildType>  Build type (choices: "localhost", "vaogvdev", "vagovstaging", "vagovprod")
--NEXT_PUBLIC_DRUPAL_BASE_URL <url>   Drupal base URL
--DRUPAL_CLIENT_ID <id>               Drupal client ID
--DRUPAL_CLIENT_SECRET <secret>       Drupal client secret
--DRUPAL_PREVIEW_SECRET <secret>      Drupal preview …
```
=> VACMS-15322: ENV/CLI follow-up

README.md
some readme cleanup. adds badges for CI workflows
n/a, only doc changes
n/a, only doc changes 
```[tasklist]
```
=> update default readme

generator-templates/query/query.hbs, package.json, packages/env-loader/src/cli-options.ts, plopfile.js, src/data/queries/event.ts, src/data/queries/headerFooter.ts, src/data/queries/newsStory.ts, src/data/queries/storyListing.ts, src/lib/drupal/drupalClient.ts, src/lib/drupal/query.ts
Relates to #283, where I disabled redis because it was causing CMS tugboat preview servers to fail, as no redis service is available there (nor does it need to be, all preview pages should be fetched fresh). This re-enables redis using an env var. I pass it to the cli via `yarn export` only, when static pages are generated.
I also updated the generator template + terminal output to better reflect the slight refactor to queries in #306 .
Verified redis did not run during `yarn dev`, verified it does run & store menu keys during `yarn export`
n/a
```[tasklist]
```
=> Redis fixin' + some small cleanup

.github/workflows/ci.yml, .github/workflows/preview.yml, envs/.env.gha, package.json, src/data/queries/tests/__snapshots__/questionAnswer.test.tsx.snap, src/lib/utils/events.test.ts
Adds a CI check for `yarn build:preview` as an early canary for CMS preview activities.
added a check to the CI workflow
CI should pass.
```[tasklist]
```
=> build the preview server output as part of CI

src/templates/layouts/event/index.tsx
Fixes an recurring error that was happening on event pages
Local testing
Go to any events page, verify that there are not recurring errors in console
```[tasklist]
```
=> Events error fix

READMEs/analytics.md, envs/.env.example, envs/.env.gha, envs/.env.prod, envs/.env.staging, envs/.env.tugboat, src/lib/analytics/index.tsx, src/pages/_document.tsx
Closes #[16501](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16501). 
locally, using `APP_ENV=staging` and `APP_ENV=prod` to verify that different GTM variables were loaded correctly.
we don't have staging or prod build pipelines yet, but locally you can change the `APP_ENV` to the desired environment.
note you will need to copy the DRUPAL_CLIENT_ID and DRUPAL_CLIENT_SECRET from your local .env. those will be stored in their respective pipeline environments.
```[tasklist]
```
=> VACMS-16501 gtm keys

src/data/queries/alert.ts, src/data/queries/alertSingle.ts, src/data/queries/index.ts, src/lib/drupal/query.ts, src/mocks/alertSingle.mock.json, src/templates/components/alertSingle/alertSingle.stories.ts, src/templates/components/alertSingle/index.test.tsx, src/templates/components/alertSingle/index.tsx, src/types/drupal/paragraph.ts, src/types/formatted/alertSingle.ts
Relates to:
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8608
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8608
Brings in queries and component for the alert_single type.  Also addresses the logic required to render Non reusable alerts in the same component.
Changes:
Adds alertSingle react component
Adds alertSingle query
Updates types and property names where necessary
Adds jest test for alert component
Adds storybook for AlertSingle
Local testing
Verify that component renders properly with storybook
Further verification when resources and support page is added and this component is actually used
=> paragraph--alert_single added, with logic for reusable and non-reusable alert types

src/data/queries/reactWidget.ts, src/mocks/button.mock.json, src/mocks/linkTeaser.mock.json, src/templates/components/reactWidget/index.test.tsx, src/templates/components/reactWidget/index.tsx, src/templates/components/reactWidget/reactWidget.stories.ts, src/types/drupal/field_type.d.ts, src/types/formatted/reactWidget.ts
Relates to: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8636
Test Locally
```
<Wrapper
bannerData={bannerData}
headerFooterData={headerFooterData}
preview={preview}
resource={resource}
>
<ReactWidget entityId={0} widgetType="pension-app-status" />
.
.
.
```
- Examples:
=> VACMS-8636: Adds component for rendering react-widget paragraph.

src/templates/components/accordion/index.tsx, src/templates/components/collapsiblePanel/index.tsx, src/templates/components/lovellSwitcher/index.tsx
TIL that the use of `className` in place of `class` in JSX does not apply to custom web components. So, accordingly, this PR updates incorrect usage throughout the repo.
=> Use `class` instead of `className` in custom web component

src/lib/utils/helpers.test.ts, src/lib/utils/helpers.ts, src/templates/components/collapsiblePanel/collapsiblePanel.stories.ts, src/templates/components/collapsiblePanel/index.tsx
Some web components document unary props (e.g. `<va-accordion bordered>`). Adding these props without values requires some conditional code that is kind of uglier than we'd like sprinkled throughout our components. This PR creates an abstraction for defining the conditional attributes in the JSX element in a relatively clean and repeatable fashion.
```
<va-accordion
{...conditionalAttr(bordered, 'bordered')}
{...conditionalAttr(!multiSelect, 'open-single')}
>
```
Mostly unrelated, this PR also updates one story in Storybook to bring it in line with the default props. `multiSelect` defaults to true on `<CollapsiblePanel>` (I initially defaulted it to false), so this updates the story to align with that.
- Unit tests added. 
- Manual testing on `<CollapsiblePanel />` in Storybook
=> Adds utility to create conditional JSX args

src/data/queries/healthServices.ts, src/mocks/healthServices.mock.json, src/templates/components/healthServices/healthServices.stories.ts, src/templates/components/healthServices/index.test.tsx, src/templates/components/healthServices/index.tsx, src/templates/components/servicesList/index.test.tsx, src/templates/components/servicesList/index.tsx, src/types/drupal/field_type.d.ts, src/types/drupal/taxonomy_term.d.ts, src/types/formatted/healthServices.ts
Relates to #[16787](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16787)
changes:
- Adds HealthServices component
- Adds services list component
- Adds unit tests for both
- Adds health services query
- Query test
- Types
Local yarn test, yarn test:types
Verify healthservices renders as expected in storybook
=> 16787 vet center health services

.github/workflows/broken-links-check.yml
all of those errors are due to timeout limit reached, even if the batch run in question appears to finish faster than reported. I think it's incorrectly timing between all the split batches, but not 100% sure.
e.g. this one fails, the failing step is reported at 40 minutes, but it actually shows just over 5 minutes in the logs:
https://github.com/department-of-veterans-affairs/next-build/actions/runs/8137087154/job/22234693639
```
All batches complete in 05:17!
Of an initial 408 pages, scanned total of 18673 links on 408 pages!
Detected 44 broken links.
```
```[tasklist]
```
- Add the `DO NOT …
=> bump timeout

src/lib/drupal/listingPages.test.ts, src/lib/drupal/listingPages.ts, src/lib/drupal/staticPaths.ts
Closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17399
Event-listing pages do not need all "paged" pages generated statically because the paging mechanism is done client side. This PR introduces some additional config and helper functions to be able to more granularly define whether a content type is a listing page that needs static generation of all "paged" pages or if it is a listing page that does not need that (but still needs other listing-page treatment).
The biggest gain here is efficiency of the build, as this PR will remove some unnecessary processing that was taking place for event-listing pages. Also important, this should make the code much more easy to follow, and a much more accurate representation of how things are structured/treated.
The biggest …
=> VACMS-17399: Adds more granular definition of listing pages

.github/workflows/mirror-images.yml, .github/workflows/update-manifest.yml
Relates to #[16863](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16863). 
Triggers manifest update from image creation workflow.
=> VACMS-16863: Trigger manifest update from image creation workflow.

.github/workflows/update-manifest.yml
Relates to #[16863](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16863). 
Previously we tried using a matrix - so 4 parallel instances - to update the 4 environments for Next Build EKS.
This doesn't work because manifest updates are a 'gitops' operation. We can't do these in parallel because it creates merge conflicts.
=> VACMS-16863: Further work on automated manifest update

src/data/queries/index.ts, src/data/queries/qaGroup.ts, src/data/queries/qaParagraph.ts, src/data/queries/qaSection.ts, src/data/queries/resourcesSupport.ts, src/data/queries/tests/__snapshots__/banners.test.tsx.snap, src/data/queries/tests/__snapshots__/qaGroup.test.tsx.snap, src/data/queries/tests/__snapshots__/qaParagraph.test.tsx.snap, src/data/queries/tests/__snapshots__/qaSection.test.tsx.snap, src/data/queries/tests/qaGroup.test.tsx, src/data/queries/tests/qaSection.test.tsx, src/lib/constants/resourceTypes.ts, src/mocks/qaGroup.mock.json, src/mocks/qaSection.mock.json, src/templates/components/paragraph/index.tsx, src/templates/components/qaCollapsiblePanel/index.test.tsx, src/templates/components/qaCollapsiblePanel/index.tsx, src/templates/components/qaCollapsiblePanel/qaCollapsiblePanel.stories.ts, src/templates/components/qaParagraph/index.test.tsx, src/templates/components/qaParagraph/index.tsx, src/templates/components/qaParagraph/qaParagraph.stories.ts, src/templates/components/qaSection/index.test.tsx, src/templates/components/qaSection/index.tsx, src/templates/components/qaSection/qaSection.stories.ts, src/types/drupal/node.ts, src/types/drupal/paragraph.ts, src/types/formatted/qaGroup.ts, src/types/formatted/qaParagraph.ts, src/types/formatted/qaSection.ts
issues:
[#8629](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8629)
[#17322](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17322)
Changes
Adds q_a_section and q_a_group queries/tests/types
adds q_a_section component with tests
adds qaCollapsible panel component with tests
modifies existing qaParagraph component and types slightly
Local Visual
verified components render on R&S pages
Verify components render as expected in storybook
Verify QA components render on R&S pages, (ie: http://localhost:3000/resources/creating-an-account-for-vagov/)
```[tasklist]
```
=> 8629 qa group section

src/data/queries/banners.ts
Relates to #[17334](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17334).
Vamc data was coming through as either an object or an array.  this normalized the data.
Verify tugboat builds without error
=> Normalize CMS banner data for vamc facilities

src/data/queries/alertSingle.ts, src/data/queries/audienceTopics.ts, src/data/queries/benefitsHubLinks.ts, src/data/queries/collapsiblePanel.ts, src/data/queries/collapsiblePanelItem.ts, src/data/queries/contactInfo.ts, src/data/queries/event.ts, src/data/queries/featuredContent.ts, src/data/queries/headerFooter.ts, src/data/queries/healthServices.ts, src/data/queries/index.ts, src/data/queries/newsStory.ts, src/data/queries/newsStoryTeaser.ts, src/data/queries/promoBlock.ts, src/data/queries/qaGroup.ts, src/data/queries/resourcesSupport.ts, src/data/queries/supportServices.ts, src/data/queries/tests/__snapshots__/contactInfo.test.tsx.snap, src/data/queries/vetCenter.ts, src/lib/utils/queries.test.ts, src/lib/utils/queries.ts
Closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17582
There was this `TODO` in [src/data/queries/alertSingle.ts](https://github.com/department-of-veterans-affairs/next-build/blob/a10b0ff1f9bab4e796d6774b073c473cd2370774/src/data/queries/alertSingle.ts#L11-L57). This PR implements a solution to this.
```
// TODO:
//
// EDIT:
// It seems *maybe* that next-drupal-query is designed to handle this already.
// You can pass an `id` to queries.getParams().
// E.g.
// queries.getParams('paragraph--alert_single'))
//
// We don't need this here:
// export const params: QueryParams<null> = () => {
//   return new DrupalJsonApiParams()
//     .addInclude([
//       'field_alert_block_reference',
//       'field_alert_block_reference.field_alert_content',
// …
```
=> VACMS-17582: Rearchitects query parameters

.github/workflows/archive.yml
Relates to https://dsva.slack.com/archives/C06DSBT7CBW/p1712129275453859
Not sure if changing the schedule will actually fix this, but it seems like an easy variable to test initially.
```[tasklist]
```
=> adjust archive workflow schedule

.github/workflows/content-release.yml
Relates to https://dsva.slack.com/archives/C01SR56755H/p1712162234520889
Change the content-release workflow to start after a new production tag is created instead of CI pass
```[tasklist]
```
=> Update content-release trigger

.github/workflows/fetch-latest-release/index.js
Relates to #498 
missed a require statement that was hidden in github actions 🤦 
failed the content release workflow because of it: https://github.com/department-of-veterans-affairs/next-build/actions/runs/8654524837
```[tasklist]
```
=> missed a require statement

next.config.js
Relates to https://dsva.slack.com/archives/C01SR56755H/p1713378034155279?thread_ts=1713369389.668769&cid=C01SR56755H
Without the `generateBuildId` key in next.config, the hash of the generated files changes each run. This is fine in theory, but in practice it means that when the content-release workflow runs and pushes files to S3, the location of some objects is different than when say, the CMS Preview Server is built inside of docker. It requests to the S3 bucket correctly via the `NEXT_PUBLIC_ASSETS_URL` environment var, but the hash it wants for certain assets at that URL is different.
Locally, I ran `yarn build --no-USE_REDIS` and `yarn build:preview`, confirmed that the hashes changed per run.
After setting the `generateBuildId` config option, the files were output with the same …
=> use generateBuildId

.github/workflows/content-release.yml
Relates to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18046
This simply adds a manual `workflow_dispatch` to the Content Release workflow. This is temporary; it will be used to facilitate development and testing for Content Release in the ticket above.
=> Add workflow dispatch trigger to content release.

package.json, packages/proxy-fetcher/src/index.ts, scripts/broken-links-slack-payload.js, scripts/test-links.js, test/getSitemapLocations.js, yarn.lock
Relates to https://dsva.slack.com/archives/C01SR56755H/p1713986665887349
run `yarn tsc -b ./packages/proxy-fetcher/tsconfig.json` to compile updates to proxy-fetcher (there was an actual bug here, we only targeted `.cms.va.gov` endpoints, not `.vfs.va.gov`)
run `SITE_URL="https://main-kqjsor0i3mjdwsy9gojxhhyvdzh0wubb.tugboat.vfs.va.gov/" node ./scripts/test-links.js`
SITE_URL can be any valid link that has a sitemap.
```
SITE_URL="https://main-kqjsor0i3mjdwsy9gojxhhyvdzh0wubb.tugboat.vfs.va.gov/" node ./scripts/test-links.js
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
```
What …
=> stub link test

.github/workflows/content-release.yml, envs/.env.dev, envs/.env.prod, envs/.env.staging
Change our environments to point to /genereated to support all platforms in order to get stylesheets to work. Also added a dev envrionment. Add support for testing code on any branch rather than a specific tag. Add change for app_env to actually specify targeted build location
I used content release to push built pages to dev. I went to dev.va.gov and this code in combination with the previous changes made in vsp-reverse-proxy I was able to prove that outreach and events worked where before it failed to load styles.
=> Change envs to work with the revproxy

.github/workflows/content-release.yml, .github/workflows/recurring-release.yml
Run recurring release for all environments. This is a quick and dirty solution to the problem. We should use the matrix strategy for this in the future but would require heavy logic changes to the content-release workflow. That documentation is here https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs.
=> Feat: recurring release on all 'environments'

src/templates/common/breadcrumbs/index.tsx
This fixes a problem we had with breadcrumbs where they were not displaying.
Checked the output on Tugboat: https://pr598-yncw2xf9nv0vjprxo8meunmgav3wf6bc.tugboat.vfs.va.gov/pittsburgh-health-care/events/70251/
=> Add uswds property to breadcrumbs so that they render.

.husky/pre-commit
This very small PR addresses a deprecation warning that has popped up since we moved to husky 9.x:
```
➜ git commit -m "Add 'build all' flag override to test environment."
husky - DEPRECATED
Please remove the following two lines from .husky/pre-commit:
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
They WILL FAIL in v10.0.0
```
This is per the husky upgrade instructions: https://github.com/typicode/husky/releases/tag/v9.0.1
None of the other upgrade instructions apply to us.
=> Remove deprecated husky command lines.

packages/env-loader/src/cms-feature-flags.ts
Just console logging a value to startup so that we can see if env vars are being loaded correctly.
=> Debug env vars on prod.

.github/workflows/content-release.yml
broken next build sitemap
This is to address a fix to the sitemap config
```[tasklist]
```
tested in my local shell and it works as expected
=> fix: Fix sitemap so that if all feature flags are disabled, the build dosen't break

next-sitemap.config.js
Currently we output a simple default robots.txt file with the next-sitemap plugin. This PR disables that so that [the existing robots.txt from Content Build](https://www.va.gov/robots.txt) continues to be used. 
#773 , indirectly. This PR does not close that ticket. 
```[tasklist]
```
1. Go to the admin for the Tugboat instance associated with this PR: https://tugboat.vfs.va.gov/66fdd05e25a4ad7d7601e0bd
2. Enter 'Terminal' for the main web preview. This may take a second if the preview is currently suspended.
3. Run `cd out && ls -al robots.txt`
If the file is not found, **the behavior is correct.** We are removing the file with this PR.
If you see a file there and it has content like the following (`less robots.txt`), this PR is not passing:
```
User-agent: *
Allow: /
Host: …
```
=> Disable robots.txt generation.

src/lib/utils/date.test.ts, src/lib/utils/date.ts
This corrects an error where a recurring event that is in progress would show the following event's date while the event was still in progress. A recurring event that is currently in progress should show the current date until the event window has passed. 
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19470
```[tasklist]
```
We are looking at this event: https://main-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/outreach-and-events/events/73053
This event runs daily through Oct 30, from 9:00 am - 5:00 pm ET, which makes it a good candidate for testing of ongoing recurring events.
1. On any given day, before 5:00 pm ET, the following URL should show 'When' as the current day: https://pr795-sqczpa1lsqkrhxqurt8pmzmjjxf2rytt.tugboat.vfs.va.gov/outreach-and-events/events/ …
=> Check for ongoing recurring events when making date-based event calculations.

next.config.js, src/data/queries/pressReleaseListing.ts, src/data/queries/storyListing.ts, src/lib/drupal/facilitySideNav.ts
These changes handle an edge case where a facility-connected page does not have an active VAMC system; see more details in the ticket.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19759
```[tasklist]
```
```[tasklist]
```
=> Handle edge case where menu is not defined.

src/pages/_document.tsx
The corrects the missing i18n text for web components. 
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19670
```[tasklist]
```
The effective code different between the last working version of the file and the new version is as follows:
```diff
diff --git a/src/pages/_document.tsx b/src/pages/_document.tsx
index c070a36f..728ac917 100644
--- a/src/pages/_document.tsx
+++ b/src/pages/_document.tsx
@@ -4,10 +4,11 @@ import Script from 'next/script'
const Document = () => {
const ASSETS_URL = process.env.NEXT_PUBLIC_ASSETS_URL || '/generated/'
+  const nonce = '**CSP_NONCE**'
return (
<Html lang="en" dir="ltr">
-      <Head>
+      <Head nonce={nonce}>
<meta charSet="utf-8" />
<link
href={`${ASSETS_URL}static-pages.css`}
@@ -20,6 +21,7 @@ const Document = () => { …
```
=> Roll back custom head & document; add nonce to head and nextscript.

envs/.env.staging
#Description
This turns on Events & Event Listings for the Staging environment (staging.va.gov). This is necessary for Collab Cycle.
=> Enable events & listings on staging.

additional.d.ts, src/templates/common/relatedLinks/index.test.tsx, src/templates/common/relatedLinks/index.tsx, src/templates/common/relatedLinks/relatedLinks.stories.ts, src/templates/common/secondaryButtonGroup/index.test.tsx, src/templates/common/secondaryButtonGroup/index.tsx, src/templates/common/secondaryButtonGroup/secondaryButtonGroup.stories.ts, src/types/formatted/relatedLinks.ts
Adds SecondaryButtonGroup and RelatedLinks components. Both of these are common across Resources & Support pages. RelatedLinks will take the place of RelatedInformation and BenefitHubsLinks.
Relates to #[19386](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19386).
```[tasklist]
```
These components aren't used anywhere yet, so you can just view them in Storybook.
```[tasklist]
```
When merging a layout, you must ensure that the content type has been turned on for …
=> VACMS-19386 Add SecondaryButtonGroup and RelatedLinks common components

.github/workflows/content-release.yml
Disable the sitemap for launch.
=> Disable sitemap generation.

.github/workflows/content-release.yml
In cases where the metrics sent from content release to Datadog are empty, they have been reporting `null` i.e. empty. This causes problems for the `jq` queries that construct the json that gets sent to Datadog, causing it to fail.
=> Insert 0 as metrics fallback if metric is empty.

.github/workflows/update-manifest.yml
- Do not use @va.gov email address
- Instead use a `noreply` email address
- Per https://github.com/orgs/department-of-veterans-affairs/discussions/13
- This technically only applies to public repos, but consistency across all repos is appreciated
=> chore: Use noreply for va-vsp-bot email

src/data/queries/banners.ts
Banner data did not contain a field we were expecting and the banner code attempted to iterate over it.
This threw an error which caused the entire page to not be built, which is a problem for us.
Visit /boston-health-care/events on this Tugboat instance; it should show a page.
=> Check banner object for field before trying to iterate over it.

src/pages/_document.tsx
Removes references to fa-solid-900.woff, which is a font file that is no longer generated.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20219
=> Remove fa-solid-900.woff reference.

.github/workflows/production-tag.yml
This installs a holiday checker for the production tag creator for Next Build. It checks for whether we are in a holiday state, and does not cut a production tag
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19910
```[tasklist]
```
This is testable from this branch for testing, both without and with the override in place.
- No override: https://github.com/department-of-veterans-affairs/next-build/actions/runs/12486271581
- Override: https://github.com/department-of-veterans-affairs/next-build/actions/runs/12486284360 (successfully passed to tag creation; workflow subsequently cancelled to not violate code freeze).
=> Add a holiday check to the production tag process, including an override.

src/templates/common/medallia/index.tsx
The Medallia script responsible for providing feedback button interactivity is not loading on production for Next Build pages.
The problem is that the build script passes in `prod` as the value for the environment, but Next Build understands `vagovprod` to be the value for that environment. This is causing the staging script to load. See https://github.com/department-of-veterans-affairs/next-build/blob/3fdc28ceb9ea0887666867257443b17a4ae5afd7/src/templates/common/medallia/index.tsx#L12
This aligns the environment test for prod with the value that is currently being passed in to the build. This will be revisited in another ticket to bring environment usage into consistency: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20270
```[tasklist]
```
This cannot be properly …
=> Use the currently passed-in value for vagovprod to load Medallia scripts.

src/templates/common/medallia/index.tsx
The Medallia script responsible for providing feedback button interactivity is not loading on production for Next Build pages.
This was addressed incorrectly in https://github.com/department-of-veterans-affairs/next-build/pull/863; this PR corrects that PR.
The env var `BUILD_TYPE` is not passed in anywhere; however, `NEXT_PUBLIC_BUILD_TYPE` is passed in. See https://github.com/department-of-veterans-affairs/next-build/blob/3fdc28ceb9ea0887666867257443b17a4ae5afd7/src/templates/common/medallia/index.tsx#L12
This aligns the environment test for prod with the value that is currently being passed in to the build. This will be revisited in another ticket to bring environment usage into consistency: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20270
```[tasklist]
``` …
=> Use correct build type env var.

src/templates/layouts/eventListing/index.tsx
This changes the data assignment of events to be `allEventTeasers` to conform to changes in https://github.com/department-of-veterans-affairs/vets-website/pull/34528/files
=> Change event teaser assignment to allEventTeasers.

src/templates/layouts/pressRelease/index.test.tsx, src/templates/layouts/pressRelease/index.tsx
This PR fixes the bug such that the Media Contacts header does no appear if there are no contacts/the array is empty. It adds extra validation and adds some tests. 
Closes #[20172](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20172)
```[tasklist]
```
For local testing
Load up http://localhost:3999/boston-health-care/news-releases/va-boston-clinical-researchers-honored-with-presidential-early-career-award/
Load up http://localhost:3999/boston-health-care/news-releases/va-new-england-healthcare-system-announces-new-deputy-executive-director/
contacts is empty in the latter and Media contacts header is missing vs in the first one it is visible
Tugboat Preview should not have Media Contacts at the bottom
Also run ` npm test -- src/templates/layouts/pressRelease`  for …
=> Fixing Media Contacts bug 

.github/workflows/content-release.yml, .github/workflows/wait-for-cms-ready/action.yml
Content Release was not checking whether the CMS is available to be used as an API before trying to build. This caused Content Release to fail to build some pages, and then to push those "failed" (i.e. empty) pages to prod, resulting in missing pages in the deploy.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20594
This is not testable from a non-`main` branch.
However, this is 100% analogous to an equivalent step in content-build:
- action: https://github.com/department-of-veterans-affairs/content-build/tree/main/.github/workflows/wait-for-cms-ready
- usage: https://github.com/department-of-veterans-affairs/content-build/blob/main/.github/workflows/content-release.yml#L159
=> Add wait-for-cms action and use in content-release.

src/constants/pagination.ts, src/templates/layouts/pressReleaseListing/index.tsx, src/templates/layouts/storyListing/index.tsx
Currently in prod CMS this field is set to 7 but in `next-build` it was set and hardcoded to 3, This PR is changing this in `next-build` to 7 to better match what is currently in prod, and adding it as a constant so in future we only have to change it in one place instead of a few as we scale this thing out. 
Closes to #[19849](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19849)
```[tasklist]
```
For local testing load up
http://localhost:3999/boston-health-care/news-releases/
http://localhost:3999/boston-health-care/stories/ (although this one does not have enough pages to see a difference)
and ensure that at the bottom the <VaPagination> component upon inspection is like
Check the footer, ensure it works
Before:
After:
- Add links to …
=> Bug Fix: changing maxPageListLength from 3 to 7 to match CMS

CODE_OF_CONDUCT.md, CONTRIBUTING.md
Adds some basic guidelines on how to contribute to the repo.
Relates to #[20317](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20317)
(Lays the groundwork for contributions, doesn't actually touch the runbook quite yet.)
=> Add a CONTRIBUTING.md and CODE_OF_CONDUCT.md

.github/workflows/content-release.yml
Content Release was not checking whether the CMS is available to be used as an API before trying to build. This caused Content Release to fail to build some pages, and then to push those "failed" (i.e. empty) pages to prod, resulting in missing pages in the deploy.
This corrects an issue with an earlier deploy: https://github.com/department-of-veterans-affairs/next-build/pull/890
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20594
This is not testable from a non-`main` branch.
However, this is 100% analogous to an equivalent step in content-build:
- action: https://github.com/department-of-veterans-affairs/content-build/tree/main/.github/workflows/wait-for-cms-ready
- usage: https://github.com/department-of-veterans-affairs/content-build/blob/main/.github/workflows/co …
=> Source CMS ready action from installation location.

.github/workflows/content-release.yml
Content Release was not checking whether the CMS is available to be used as an API before trying to build. This caused Content Release to fail to build some pages, and then to push those "failed" (i.e. empty) pages to prod, resulting in missing pages in the deploy.
This corrects an issue with an earlier deploy: https://github.com/department-of-veterans-affairs/next-build/pull/892
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20594
This is not testable from a non-`main` branch.
However, this is 100% analogous to an equivalent step in content-build:
- action: https://github.com/department-of-veterans-affairs/content-build/tree/main/.github/workflows/wait-for-cms-ready
- usage: https://github.com/department-of-veterans-affairs/content-build/blob/main/.github/workflows/co …
=> Vacms 20594 wait for cms

src/data/queries/pressReleaseTeaser.ts, src/data/queries/tests/__snapshots__/pressReleaseTeaser.test.tsx.snap, src/data/queries/tests/pressReleaseTeaser.test.tsx, src/lib/utils/helpers.test.ts, src/lib/utils/helpers.ts, src/mocks/formattedPressReleases.mock.js, src/templates/components/pressReleaseTeaser/index.test.tsx, src/templates/components/pressReleaseTeaser/index.tsx, src/types/formatted/pressRelease.ts
This PR addresses 2 seperate issues resulting in some date mismatches in `next-build` that are not related to each other:
1. Changing the date from `field_last_saved_by_an_editor` to `field_release_date` to maintain parity with Prod CMS/content build. (First 2 instances in the ticket)
2. changing the `formate_date` function in `next-build` to have a timezone parameter and set that to UTC by default rather than system time (last example in the ticket)
Relates to #[20150](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20150).
```[tasklist]
```
For case #1 
For case #2 
check the dates and ensure there is parity 
What variations of circumstances (users, …
=> Release Date bug fix to maintain parity with prod CMS

.github/workflows/content-release-prod.yml
Content release to prod is meant to happen every 30 minutes between 8 am and 8 pm ET. However, we do not want to run content release at 3:30 pm ET, because CMS deploy happens then and we have seen build failures relating to CMS being offline.
This PR also corrects the start time; before this PR, it was starting at 7 am ET. This was probably a remnant of Daylight Saving Time; also, cron syntax can be confusing.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20644
```[tasklist]
```
The cron syntax should be reviewed by someone familiar with cron syntax to confirm. We will not be able to test this until merge to `main`, as [cron scheduling for GHA jobs is only available on the `main` branch](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow- …
=> Correct cron time and do not run at 3:30 pm ET.

.github/pull_request_template.md
Tasklists are being retired. See https://github.blog/changelog/2025-02-18-github-issues-projects-february-18th-update/#tasklist-blocks-will-be-retired-and-replaced-with-sub-issues.
=> Update pull_request_template.md to remove tasklist syntax

src/templates/common/socialLinks/index.tsx, src/templates/components/personProfile/index.test.tsx, src/templates/components/personProfile/index.tsx, src/templates/components/storyListingLink/index.test.tsx, src/templates/components/storyListingLink/index.tsx
This PR addresses 3 small bug fixes including - 
- Encapsulating "See all stories" in a `va-link` `<p>` tag
- correct margin on share links for facebook and twitter on story detail page
- have correct tag and margin on the author byline aka Byline text is wrapped in a single `<p>` tag with only vads-u-margin-bottom--0p5 and vads-u-font-weight--bold classes
Relates to #[20557](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20557)
Relates to #[20558](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20558)
Relates to #[20559](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20559)
```
```
QA review of this behavior and inspect elements 
Before:
After:
Before:
After:
Before:
After:
- Add links to …
=> Stories Pages defects

src/pages/_playground/api-explorer.tsx, src/pages/api/drupal-query.ts
Adds a filter option to the API explorer so we can find entities that have the data we need to reshape.
This pull request introduces a new filtering feature to the API Explorer, allowing users to add, remove, and update filters for their queries. The changes include modifications to both the frontend and backend to support this new functionality.
* Added a new `Filter` interface and integrated it into the `QueryState` interface. [[1]](diffhunk://#diff-f7fabf4e20e95c192c9124c7be6cd43bf315666f1c091c2be8f67fc03fcfba64R71-R76) [[2]](diffhunk://#diff-f7fabf4e20e95c192c9124c7be6cd43bf315666f1c091c2be8f67fc03fcfba64R90)
* Modified the initial state of `queryState` to include an empty `filters` array and changed the default `pageLimit` value.
* Implemented `addFilter`, `removeFilter`, and …
=> Add a filter option to the api explorer

.github/pull_request_template.md
The PR template as it was made it cumbersome to go from the ticket to the implementation PR. Just pasting in the link directly makes this navigation easier and triggers the auto-close feature in GitHub, updating our project board appropriately.
Along the way, my markdown auto-formatter added some spaces to make the linter a little happier, and I added code fence languages to the weirdly-code-fenced blocks. 🤷 Again, all to serve Lord Linter, the Marquis of Markdown.
See [this PR](https://github.com/department-of-veterans-affairs/next-build/pull/929) and [this issue](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20765).
Linking directly looks like this in the PR:
And in the linked issue:
=> Update PR template to link directly to the ticket

src/templates/components/hours/index.test.tsx, src/templates/components/hours/index.tsx
This takes the displaying of Hours (currently only used by Vet Centers) and updates it to the latest designs. Additionally, it adds `nonTraditionalHours` to handle the displaying of those for Vet Centers and their Outstations
This pull request introduces a new header type `nonTraditionalHours` to the `Hours` component and updates the corresponding tests and styles.
Key changes include:
* [`src/templates/components/hours/index.tsx`](diffhunk://#diff-1f88527a9c3897b8c85fa207a31b9a2ce024830fab5f0d957b71b138f8b2f708R65-R76): Added a new case for `nonTraditionalHours` in the `Hours` component to display a specific message about non-traditional hours.
* [`src/templates/components/hours/index.tsx`](diffhunk://#diff-1f88527a9c3897b8c85fa207a31b9a2ce024830fab5f0d957b71b138f8b2f708L5-R10): Updated …
=> [VACMS-20706]Adjust Vet Center hours display to latest design, add nonTraditionalHours

src/templates/components/hours/hours.stories.ts, src/templates/components/hours/index.test.tsx, src/templates/components/hours/index.tsx, src/templates/layouts/vetCenter/index.tsx
Moves the displaying of Vet Center `nonTraditionalHours` messages by passing it along to the `Hours` component. This is being done so that the message can be displayed above the hours and below the header, per the latest designs.
This pull request includes changes to the `Hours` component and its associated files to support a new `nonTraditionalMessage` property. The most important changes include adding the `nonTraditionalMessage` property to the `Hours` component, updating the corresponding stories and tests, and removing the previous handling of non-traditional hours.
Changes to the `Hours` component:
* [`src/templates/components/hours/index.tsx`](diffhunk://#diff-1f88527a9c3897b8c85fa207a31b9a2ce024830fab5f0d957b71b138f8b2f708R2-R15): Added the `nonTraditionalMessage` property to the …
=> [VACMS-20945]Display Vet Center nonTraditionalHours warning above hours

additional.d.ts, src/templates/common/featuredContent/index.test.tsx, src/templates/common/featuredContent/index.tsx, src/templates/components/paragraph/index.test.tsx, src/templates/components/qaSection/index.tsx, src/templates/layouts/vetCenter/index.test.tsx, src/templates/layouts/vetCenter/index.tsx
Brings Vet Center components up to date with latest designs [here](https://www.figma.com/design/EVd3q06ukAbVS61Q8MwRAT/Vet-Centers?node-id=1790-8784&t=hm7pw0FEJZzIMMCs-1)
Updates the Vet Center Featured Content to no longer have a blue background and instead an arrow pointing towards the link. Additionally, adds an ID to the qa section so that it can be capture by the "on this page" component.
This pull request includes several updates to the `FeaturedContent` component and its associated tests, as well as some changes to the `QaSection` component. The main changes involve updating the structure and attributes of the `FeaturedContent` component, adding utility functions, and modifying test cases to reflect these updates.
* Updated the `FeaturedContent` component to use the `va-link` …
=> [VACMS-20706]Adjust Vet Center components to latest designs

.tugboat/config.yml, scripts/yarn/vets-website-assets.js
This fixes a problem where fonts were neither being downloaded to Tugboat nor able to be referenced from an S3 asset bucket.
This pull request includes updates to the build configuration and asset management scripts to support a new build type, `tugboat`, and improve the copying of asset files.
* [`.tugboat/config.yml`](diffhunk://#diff-fbd0812762ff8d2c67fa66a4956c3b55557ad0889505294f524192000b2ce50eL67-R67): Changed the `BUILD_TYPE` from `vagovprod` to `tugboat` to accommodate the new build type.
* [`scripts/yarn/vets-website-assets.js`](diffhunk://#diff-a52b6e021d8aeb65157b69c6a3681c8c067c8f88011ed8ecb15b87bebab72f2aR35): Added a new `tugboat` option to the `BUILD_TYPE_BUCKET` to map it to the `devBucket`.
* [`scripts/yarn/vets-website-assets.js`](diffhunk://#diff-a52b6e021d8aeb65157b69c …
=> Modifications to ensure fonts are downloaded to Tugboat instances.

src/templates/layouts/healthCareLocalFacility/OperatingStatus.test.tsx, src/templates/layouts/healthCareLocalFacility/OperatingStatus.tsx, src/templates/layouts/healthCareLocalFacility/index.test.tsx, src/templates/layouts/healthCareLocalFacility/index.tsx, src/types/drupal/node.ts
Adds the little operational status alert banner when needed.
This pull request includes significant changes to the `healthCareLocalFacility` layout to implement and test the `OperatingStatusFlags` component. The updates involve adding new status types, integrating the component into the layout, and ensuring comprehensive test coverage.
* **`OperatingStatusFlags` Component:**
- Added a new `OperatingStatusFlags` component to handle various facility operating statuses and display appropriate alerts.
- Integrated the `OperatingStatusFlags` component into the `HealthCareLocalFacility` layout.
* **Unit Tests for `OperatingStatusFlags`:**
- Created unit tests for the `OperatingStatusFlags` component to verify rendering based on different operating statuses.
* **Mock Data Adjustments:**
- …
=> Operational status flags

src/data/queries/healthCareLocalFacility.ts, src/data/queries/tests/__snapshots__/healthCareLocalFacility.test.tsx.snap, src/templates/components/topTasks/index.test.tsx, src/templates/components/topTasks/index.tsx, src/templates/layouts/healthCareLocalFacility/index.test.tsx, src/templates/layouts/healthCareLocalFacility/index.tsx, src/types/formatted/healthCareLocalFacility.ts
Adds the top tasks links to the page
This pull request includes several changes to enhance the handling of `TopTasks` for health care local facilities by adding new properties and updating tests accordingly. The most important changes include adding new fields to the data queries, updating the `TopTasks` component, and modifying the corresponding tests.
* [`src/data/queries/healthCareLocalFacility.ts`](diffhunk://#diff-35c09c75baec6b07a198e9d78d40d7db3a47ac9fc1c9a1e68a3566c1faf7303fR83-R87): Added `path`, `administration`, and `vamcEhrSystem` fields to the data formatter.
* [`src/templates/components/topTasks/index.tsx`](diffhunk://#diff-b6ed2ed533f30ca9eb50c03864762acaea39a821a77f65e7336d3757a18ae82aR1-R131): Created the `TopTasks` component to display actionable links for a facility, …
=> VAMC Facilities: Top tasks

src/templates/common/contentFooter/index.tsx, src/templates/common/medallia/index.test.tsx, src/templates/common/medallia/index.tsx
A bit of a lift and shift of the medallia event listeners from content-build
This pull request includes several updates to the `MedalliaAssets` component and its associated tests to improve event handling and analytics recording. The most important changes include adding the `recordEvent` function, implementing event listeners for various Medallia events, and updating the test cases to mock and verify these events.
* [`src/templates/common/medallia/index.tsx`](diffhunk://#diff-5cdda7136985d4843bf8f9b7f45b1ea45c1e29d17657c729f9fae7a9ad47266cR10): Added the `recordEvent` function and implemented event listeners for various Medallia events, such as `ShowForm_Called`, `Form_Displayed`, `Feedback_Submit`, and others, to record analytics data. …
=> VACMS 19771 feedback analytics

generator-templates/component/playwright.hbs, playwright/tests/eventListing.spec.ts, playwright/tests/healthCareLocalFacility.spec.js, playwright/tests/newsStory.spec.ts, playwright/tests/pressRelease.spec.ts
This removes a test, corrects some, skips others, and updates the generator template so that generated tests do not run by default.
This pull request includes changes to several Playwright test files, primarily focusing on modifying or skipping tests and updating test URLs. The most important changes include skipping tests that need modifications, updating test selectors, and changing test URLs to more relevant ones.
Test modifications:
* [`playwright/tests/eventListing.spec.ts`](diffhunk://#diff-ff501ffac4380c8c0bee51b4fe902e245ebcf4a085ead8cd5f1f28dda7c831a9L12-R13): Removed a test for the Event Listing widget that was causing errors and updated another test to run without skipping.
* [`generator-templates/component/playwright.hbs`](diffhunk://#diff-50dc009710de3531e6d9195514a75e24706244 …
=> Minor tweaks to get Playwright tests running.

scripts/migrate-grid.mjs
Adds a script to migrate to v3 grid.
This pull request introduces a new script `migrate-grid.mjs` to automate the migration of CSS class names from the old grid system to the new one, along with a dry-run feature for testing changes without modifying files. Below are the key changes:
**New Script Addition:**
* [`scripts/migrate-grid.mjs`](diffhunk://#diff-c4661b05cdb67e59b36fbf247a2998bc15ce8a516790cf6abbd82eacc1eaf742R1-R137): Added a new script to handle the migration of CSS class names with specific mappings, prefix replacements, and breakpoint replacements. This script also includes functionality to warn about deprecated Foundation classes and remove duplicate class names.
**Migration Functionality:**
* Implemented exact, prefix, and breakpoint replacements for CSS class names to …
=> VADS grid migration script

.github/CODEOWNERS
Adds Next Build Product as a code owner of `src/templates`, in order to force visual/business logic review of changes.
This pull request includes a small change to the `.github/CODEOWNERS` file. The change assigns ownership of the `src/templates` directory to the `next-build-product` team for verification by product owners.
* [`.github/CODEOWNERS`](diffhunk://#diff-3d36a1bf06148bc6ba1ce2ed3d19de32ea708d955fed212c0d27c536f0bd4da7R11-R14): Added `src/templates` to be verified by the `next-build-product` team.
=> Update CODEOWNERS to give  Next Build Product visibility over templates.

src/data/queries/personProfile.ts, src/data/queries/tests/__snapshots__/personProfile.test.tsx.snap, src/templates/layouts/staffProfile/index.test.tsx, src/templates/layouts/staffProfile/index.tsx, src/templates/layouts/staffProfile/staffProfile.stories.ts, src/types/formatted/staffProfile.ts
Address defects found in the staff profile page.
This pull request refactors the `StaffProfile` component and related files to improve naming consistency, enhance functionality, and update tests. The key changes include renaming a property for clarity, adding new functionality for file downloads, and updating tests to reflect these changes.
* Renamed `vamcOfficalName` to `vamcTitle` across multiple files to improve naming consistency and clarity. (`src/data/queries/personProfile.ts` [[1]](diffhunk://#diff-fb3c28fd960889f40581d6766daac0d2e97708113468b12a0492394c71361c39L79-R87) `src/templates/layouts/staffProfile/index.tsx` [[2]](diffhunk://#diff-d74274c7a72eef4771791e64dc3cd75049dc232c9eeed07c1fef3da1e188f998L25-R31) [[3]](diffhunk://#diff-d74274c7a72eef4771791e64dc3cd75049dc232c9eeed07c1f …
=> Staff profile defects

src/templates/layouts/staffProfile/index.tsx
Changes `vads-u-width--full` (width: 100%) to `vads-u-width--auto` (width: auto) to maintain the aspect ratio of headshot down to mobile sizes. 
This pull request includes a small update to the `StaffProfile` component to adjust the styling of the media image.
* [`src/templates/layouts/staffProfile/index.tsx`](diffhunk://#diff-d74274c7a72eef4771791e64dc3cd75049dc232c9eeed07c1fef3da1e188f998L55-R55): Changed the `className` property of the `MediaImage` component from `vads-u-width--full` to `vads-u-width--auto` to modify the image's width behavior.
Closes [21150](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/21150#issuecomment-2821245181)
- visit https://pr987-2hccpeuw4d1qba9umzxxwqbqtlj2wuac.tugboat.vfs.va.gov/boston-health-care/staff-profiles/vincent-ng/
- in …
=> Fix mobile aspect ration for profile headshot

next.config.js
Inserting the nonce for CSP when the request is fulfilled from Nextjs
[#21188](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/21188)
Closes _link to ticket_
```md
```
What needs to be checked to prove this works?
What needs to be checked to prove it didn't break any related things?
Before:
After:
---
```md
```
When merging a layout, you must ensure that the content type has been turned on for `next-build` in the [.tugboat.env](../envs/.tugboat.env). This method …
=> fixing the nonce insert issue by disabling the compression on Nextjs

src/pages/[[...slug]].tsx
It's not the prettiest logging, but I'm throwing this in here so we can see what content types we're building, how many pages each type has, and how long it takes to fetch that path data.
We can clean up the output here some, but we're still gonna run into the "Collecting page data..." bit getting in our way. There's probably some way around that with `process.stdout.write()` and some funny terminal escape codes to backspace, but... 🙈 I've done it before, and it was ugly. Makes the logs kinda messy here, but they already are, and they're only meant to be human readable anyhow, so 🤷 . In this case, I'm favoring a little messier logs over a little messier code. I have no strong opinions, though.
This pull request introduces logging and performance measurement to the `getStaticPaths` …
=> Add logging to getStaticPaths

playwright/tests/pressReleaseListing.spec.ts, playwright/tests/storyListing.spec.ts, src/lib/drupal/listingPages.test.ts, src/lib/drupal/listingPages.ts
Fixes regex to correctly match multi-digit page numbers (e.g. page-10), not just single digits.
This pull request improves handling of double-digit page numbers for listing pages and press release pages, ensuring proper functionality in both tests and application logic. Key changes include the addition of new test cases, updates to slug definitions, and a bug fix in the page number regex.
* Added tests in `playwright/tests/pressReleaseListing.spec.ts` to validate navigation and item counts for double-digit pages in press release listings.
* Added tests in `playwright/tests/storyListing.spec.ts` to validate navigation and item counts for double-digit pages in story listings.
* Extended tests in `src/lib/drupal/listingPages.test.ts` to cover handling of double-digit page numbers for both …
=> Fixing Pagination Regex

src/templates/common/breadcrumbs/index.tsx, src/templates/components/staffProfileSideBarNav/index.tsx, src/templates/layouts/staffProfile/index.test.tsx, src/templates/layouts/staffProfile/index.tsx
Updates classnames to utilize v3 grid. 
This pull request refactors the layout and styling of the staff profile page to improve responsiveness and consistency. Key changes include updates to the sidebar navigation, grid layout, and styling adjustments for better alignment with design standards.
* Updated the `StaffProfileSideBarNav` component to remove the `usa-width-one-fourth` class and added a new `vads-u-margin--0` class to the `<h4>` element for consistent spacing. (`src/templates/components/staffProfileSideBarNav/index.tsx`, [src/templates/components/staffProfileSideBarNav/index.tsxL33-R37](diffhunk://#diff-534e7f0e3579d6bc8b1785e073cbaf6a6c64c4857701e46cc0c14a1b365bfeabL33-R37))
* Refactored the `StaffProfile` layout to use `vads-grid-container` and `vads-grid-row` for better grid …
=> Staff profile to v3 grid

src/templates/components/newsStoryTeaser/index.test.tsx, src/templates/components/newsStoryTeaser/index.tsx, src/templates/components/pressReleaseTeaser/index.test.tsx, src/templates/components/pressReleaseTeaser/index.tsx, src/templates/layouts/vetCenterOutstation/index.tsx
This PR makes the va-link self closing in some files across the codebase.
This pull request updates the usage of the `<va-link>` component across multiple files to simplify its implementation and improve test coverage. The primary changes involve replacing the child-based `<va-link>` structure with a self-closing tag that uses the `text` attribute, and updating corresponding tests to validate the new structure.
* [`src/templates/components/newsStoryTeaser/index.tsx`](diffhunk://#diff-a3a22c710561bd7dd66963d62b553b4935257d0a1fa53833f70f58a1cc35d08aL23-R23): Refactored the `<va-link>` component to use a self-closing tag with the `text` attribute instead of wrapping the title as a child.
* [`src/templates/components/pressReleaseTeaser/index.tsx`](diffhunk://#diff-a52f541f81ba799f267e6125ab0cf …
=> VACMS-20166: Making va-links self closing

READMEs/preview.md
Quick readme update related to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/21229
This pull request updates the `preview.md` documentation to include instructions for managing Drupal roles and scopes for Next.js previews.
Documentation updates:
* [`READMEs/preview.md`](diffhunk://#diff-937f10d9a3a8d824f7bbfd068c9e5e98cb5bcd5f1511b23c92db81ba41862533R54-R57): Added a new section titled "Drupal scope" that explains the process of creating and managing scopes in Drupal for roles requiring access to Next.js previews. This includes creating a scope, exporting it in configuration, deploying it to production, and manually adding it to the consumer on production since consumers are database entities.
relates to [21229](https://github.com/department-of-veterans-affairs/va.gov …
=> Update to readme for scopes in next preview.

.tugboat/config.yml, envs/.env.tugboat
This PR removes the tugboat variable from the SITE_URL in the tugboat env file. The value is now replaced during the tugboat build step before the `yarn export` happens. This makes sure that the var and files all exist but nothing has been built yet.
This pull request updates the configuration for Tugboat previews to properly handle the site URL. The changes ensure that the `SITE_URL` placeholder is replaced dynamically during the build process.
* [`.tugboat/config.yml`](diffhunk://#diff-fbd0812762ff8d2c67fa66a4956c3b55557ad0889505294f524192000b2ce50eR62-R64): Added a `sed` command in the build step to replace the placeholder `replace-with-tugboat-url` with the actual `${TUGBOAT_DEFAULT_SERVICE_URL}` in the `.env.tugboat` file.
* …
=> VACMS-19211 - update SITE_URL at build

READMEs/preview.md
There was a typo in the link to consumer
This pull request updates the documentation in `READMEs/preview.md` to include guidance on managing Drupal scopes for Next.js previews.
* Added a section explaining the process for creating and managing a Drupal scope when a new role is added, including steps for exporting the configuration and updating the consumer on production. (`[READMEs/preview.mdR54-R57](diffhunk://#diff-937f10d9a3a8d824f7bbfd068c9e5e98cb5bcd5f1511b23c92db81ba41862533R54-R57)`)
Relates to 21229
---
```md
```
When merging a layout, you must ensure that the content type has been turned on for `next-build` in the [.tugboat.env](../envs/.tugboat.env). This method mocks the CMS flag …
=> VACMS 21229 next doc typo fix

src/lib/drupal/lovell/tests/mockData.ts, src/templates/components/staffNewsProfile/index.test.tsx, src/templates/components/staffNewsProfile/index.tsx, src/templates/layouts/newsStory/index.test.tsx, src/templates/layouts/newsStory/index.tsx, src/templates/layouts/newsStory/newsStory.stories.ts
This PR fixes the author byline, adding a guard to ensure By appears only when certain fields for author exists, and to display full name and title if present, and adds tests.
This pull request refactors the handling of author data across components and tests, transitioning from a single `title` field to separate `field_name_first` and `field_last_name` fields, with an optional `field_description`. It also introduces a null return for cases where no name is provided. The changes ensure consistency and improve flexibility in managing author-related information.
* [`src/lib/drupal/lovell/tests/mockData.ts`](diffhunk://#diff-4b318176fc5bab9cab860ecad27a0a1524485b20fa5211f9cef76cb293e2ddd1L73-R74): Updated mock data to replace the `title` field with `field_name_first` and `field_last_name` …
=> Fix author by line logic

src/templates/layouts/healthCareLocalFacility/index.tsx
Fixes the URLs for the top tasks section using `path.split('/')[1]`. It's...not my favorite, but it's what `content-build` does, so it should be consistent? I'd rather use `entity.field_region_page.path.alias`, but I don't know if that'll be true for every facility.
This pull request introduces a minor update to the `HealthCareLocalFacility` component in `src/templates/layouts/healthCareLocalFacility/index.tsx`. The changes include extracting a region base path from the `path` variable and using it in the `TopTasks` component.
* Added logic to extract the base URL path of a health care region from the `path` variable using `path.split('/')[1]`. A note was included suggesting a potential alternative approach using `entity.field_region_page.path.alias`.
* Updated the `TopTasks` component to …
=> Fix the top task URLs

.github/CODEOWNERS
Removes the FE CoP from the `CODEOWNERS` file.
This pull request updates the `.github/CODEOWNERS` file to streamline ownership assignments by removing the Front-End Community of Practice (FE COP) from several areas and clarifying team responsibilities.
* Removed `@department-of-veterans-affairs/va-platform-cop-frontend` as a code owner for general ownership, front-end templates, and specific product directories, leaving `@department-of-veterans-affairs/ap-team` as the sole owner in these areas.
These changes simplify the ownership structure and reduce overlap in code review responsibilities.
Closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/21236
=> Remove FE CoP from CODEOWNERS

src/data/queries/healthCareLocalFacility.ts, src/data/queries/tests/__snapshots__/healthCareLocalFacility.test.tsx.snap, src/data/queries/tests/healthCareLocalFacility.test.tsx, src/templates/layouts/healthCareLocalFacility/index.tsx, src/types/formatted/healthCareLocalFacility.ts
Adds the LovellSwitcher component to HealthCareLocalFacility. This switch should only display for one local facility `captain-james-a-lovell-federal-health-care-center` all other local Lovell facilities are either specifically `tricare` for `va` and do not have a variant. 
The LovellSwitcher component already does not render if a switchPath is missing. To insure the switchPath is only set for `captain-james-a-lovell-federal-health-care-center`, the formatter has been updated to look at the `field_main_location` field from Drupal to determine if it is processing the main facility. All other Lovell attributes are still present for non-main facilities.
Closes [20864](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20864)
This pull request introduces functionality to …
=> VACMS-20864: Lovell switcher healthCareLocalFacility

playwright/tests/event.spec.ts, playwright/tests/eventListing.spec.ts, playwright/tests/newsStory.spec.ts, playwright/tests/pressRelease.spec.ts, playwright/tests/pressReleaseListing.spec.ts, playwright/tests/storyListing.spec.ts
Getting our playwrite tests to be green. Added a clause to wait up to 60 seconds for just the HTML content to load and be parsed not wait for all images or external assets to hopefully optimize it. Saw it 
https://playwright.dev/docs/api/class-page#page-goto-option-wait-until
and seemed to work sufficiently for this case.
This pull request updates several Playwright test files to improve page load reliability by adding options to `page.goto` calls and removes redundant pagination tests. The key changes are grouped into two themes: **Improved Page Load Handling** and **Test Simplification**.
* Updated all `page.goto` calls across multiple test files (`event.spec.ts`, `eventListing.spec.ts`, `newsStory.spec.ts`, `pressRelease.spec.ts`, `pressReleaseListing.spec.ts`, and …
=> Trying to get playwrite to be green again

src/pages/[[...slug]].tsx, src/test/slug.test.tsx
This PR fails the build when the `RESOURCE_TYPES_TO_BUILD` array is empty. It adds a guard to exit before the resource types are built so that we can exit if there are none. This came out as a weird blip when the build failed when drupal was unavailable but somehow was still waking up when it tried to build an empty array and failed silently. 
This pull request includes a small but important change to the `src/pages/[[...slug]].tsx` file. It adds a check to ensure that `RESOURCE_TYPES_TO_BUILD` is not empty before proceeding, logging an error and exiting the process if no resource types are returned.
* `src/pages/[[...slug]].tsx`: Added a validation step to log an error and terminate the process if `RESOURCE_TYPES_TO_BUILD` is empty, ensuring proper handling of missing resource types. …
=> Fail the build on empty resource types

src/data/queries/tests/__snapshots__/vamcSystemVaPolice.test.tsx.snap, src/data/queries/tests/vamcSystemVaPolice.test.tsx, src/data/queries/vamcSystemVaPolice.ts, src/mocks/vamcSystemVaPolice.mock.json, src/templates/layouts/vamcSystemVaPolice/index.test.tsx, src/templates/layouts/vamcSystemVaPolice/index.tsx, src/types/formatted/vamcSystemVaPolice.ts
This finishes the scaffolding of VAMC System VA Police page.
This pull request introduces a new feature to support the `VAMC_SYSTEM_VA_POLICE` content type, including its integration into the codebase, test coverage, and feature flag configuration. The changes span multiple files to enable data fetching, formatting, rendering, and testing for this new content type.
* Added `FEATURE_NEXT_BUILD_CONTENT_VAMC_SYSTEM_VA_POLICE=true` to `envs/.env.test` and `envs/.env.tugboat` to enable the feature in specific environments. [[1]](diffhunk://#diff-e75bb93390eacf9e914ed4ca735dd499f1ccf7e35263609813f3466952a02595R36) [[2]](diffhunk://#diff-831aaee303b0dc99e20f0f512c2c921d217fd2441d33ee0913caf2d5a88030b7R53)
* Introduced `vamcSystemVaPolice` query in `src/data/queries/vamcSystemVaPolice.ts` to …
=> VACMS-20871: Police menu and markup

src/templates/layouts/vamcSystem/ManageYourHealthLinks.test.tsx, src/templates/layouts/vamcSystem/ManageYourHealthLinks.tsx, src/templates/layouts/vamcSystem/index.tsx
- Adds the "Manage your health online" section to VAMC System page
- Fixes the weird border issues that were called out in the ticket
- Uses `<p>` tags instead of `<div>` tags (also callled out in the ticket)
Closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/21252
See ticket for testing URLs and a screenshot of the section in question
=> Add manage-your-health links section to VAMC System page

.gitignore, .repomixignore, repomix.config.json
Adds a [repomix](https://github.com/yamadashy/repomix) config for plugging into the likes of ChatGPT.
It's a low-hanging fruit for incorporating some AI into template migration and can be useful for things like describing what you need and seeing if there's already an existing component that does what you want. I intend to use it to help out with template migration.
=> Add repomix config

src/data/queries/locationsListing.ts, src/data/queries/tests/__snapshots__/locationsListing.test.tsx.snap, src/data/queries/tests/locationsListing.test.tsx, src/templates/layouts/locationsListing/index.test.tsx, src/templates/layouts/locationsListing/index.tsx, src/types/formatted/locationsListing.ts
Adds the SideNav to the locations listing scaffolded page.
This pull request introduces enhancements to the `LocationsListing` query and layout, focusing on integrating sidebar navigation functionality and improving data formatting. The most significant changes include adding support for a structured sidebar menu, updating the query logic to fetch and format menu data, and modifying the `LocationsListing` layout to render the sidebar navigation dynamically.
* **Query updates in `src/data/queries/locationsListing.ts`:** Modified the `params` function to include `field_office` in the query and updated the `data` loader to fetch and return menu data alongside the entity. Added error handling for missing entities and introduced the `LocationsListingData` type to encapsulate both entity and …
=> Locations Listing Sidenav

src/templates/common/relatedLinks/index.test.tsx, src/templates/common/relatedLinks/index.tsx
The "Other services" links were missing custom analytics events that are present in production. The links in [the original template](https://github.com/department-of-veterans-affairs/content-build/blob/0a5b0ab4db49c212b77ff2e54d8da78b29fcf55d/src/site/paragraphs/facilities/list_of_link_teasers_facility.drupal.liquid#L54) were calling a `recordEvent` function, to which we already have an analog in next-build. I've updated the component for this section to call it with the same parameters.
Closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/21522
I'm not sure if there's a better way to test the analytics events, but I was adding a console log to [the event function](https://github.com/department-of-veterans-affairs/next-build/blob/pwolfert/related-links-event/src/lib/a …
=> Send an event via `recordEvents` like the original

src/data/queries/vamcSystemVaPolice.ts, src/types/drupal/node.ts, src/types/formatted/vamcSystemVaPolice.ts
Adds Lovell variant breadcrumb.
This pull request updates the `vamcSystemVaPolice` query and related types to incorporate support for Lovell variant pages. The changes include adding breadcrumbs handling for Lovell variants, extending type definitions, and modifying the query formatter to include new data fields.
* **Breadcrumbs for Lovell variant pages**: Added logic to modify breadcrumbs when the page is identified as a Lovell variant. This is handled using the `getLovellVariantOfBreadcrumbs` function. (`[src/data/queries/vamcSystemVaPolice.tsL66-R80](diffhunk://#diff-11afa3bd343eba8224d394fe15756ee7dd351d577763900ad71120f6e9e0bf3cL66-R80)`)
* **Return updated data fields**: The query now returns `lovell` data from the `opts.context` to support Lovell-specific functionality. …
=> VACMS-21550: Adds Lovell variant breadcrumb

src/templates/common/googleMapsDirections/index.tsx
Removing this unused and duplicate id. This component is rendered multiple times on vamc system pages, which results in that id showing up multiple times in the DOM.
The GoogleMapsDirections component had a hardcoded id="google-map-directions" attribute, which caused duplicate IDs when the component was used multiple times on the same page. This violates HTML standards and creates accessibility issues.
Removed the hardcoded id="google-map-directions" attribute from the va-link element in the GoogleMapsDirections component.
- Pages affected: Event pages and facility pages that display multiple Google Maps direction links
- Accessibility: Eliminates duplicate ID violations that could interfere with screen readers and other assistive technologies
- HTML validation: Pages now pass HTML …
=> Remove unused id that is repeated in the DOM

src/templates/layouts/healthCareLocalFacility/index.tsx, src/templates/layouts/locationsListing/index.tsx, src/templates/layouts/questionAnswer/index.tsx, src/templates/layouts/resourcesSupport/index.tsx
Removes the duplicate `id="content"`.
All these components are rendered from `ResourcePage` in (`[[...slug]].tsx`) which renders a `div#content` already.
Closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/21605
=> fix: remove duplicate id

src/templates/layouts/vetCenter/index.tsx
Removes unnecessary classes on the `on-this-page` (table of contents) component. The web component itself has some internal padding that causes the text inside to be misaligned with the left edge of the page content, but that's how it is in production. Maybe in the future we could give it some negative margin or something to align the edge properly.
Closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/21557
[Explain the steps needed for testing](http://localhost:3999/boston-vet-center/)
It's hard to tell, but in the after shot, it's shifted less to the right.
Before:
After:
=> Vets Center: Remove extra utility classes

src/templates/layouts/vetCenter/index.test.tsx, src/templates/layouts/vetCenter/index.tsx
These changes correct some small defects in the "Also called" subtitle of the Vets Center pages, which shows the official name of the vets center as opposed to its common name.
Closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/21554
- Visit http://localhost:3999/st-paul-vet-center/ and check the page title and the `<p>` element below it. Should have an `aria-describedby` on the title that points to the subtitle element. 
- If you go to http://localhost:3999/boston-vet-center/, you should find that the title doesn't have an `aria-describeby` attribute, because there's nothing to point to.
Also check the ticket for details about intended behavior.
Before:
After:
=> Vets Center: Correct defects in "Also called" subtitle

src/assets/styles/globals.css
The `va-button` web component uses USWDS styles which has a right margin. When the button is used in a way that makes it right aligned to content (like the feedback button), this right margin should be removed. For those special scenarios, the web component has a `part` attribute that can be styled through the shadow dom. That is what this PR is doing for the feedback button.
Here is the feedback button in question: 
https://github.com/department-of-veterans-affairs/next-build/blob/ec31c5b604e7d5c2d35330967d66c957fc0dd047/src/templates/common/contentFooter/index.tsx#L47-L61
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3458
```md
```
What needs to be checked to prove this works? 
- Review the feedback …
=> VADS 3458: remove right margin from feedback button

additional.d.ts, src/data/queries/vetCenter.ts, src/lib/utils/getHtmlFromDrupalContent.test.ts, src/lib/utils/getHtmlFromDrupalContent.ts, src/lib/utils/getHtmlFromField.ts, src/lib/utils/helpers.test.ts, src/lib/utils/helpers.ts, src/templates/layouts/vetCenter/ExpandableOperatingStatus.test.tsx, src/templates/layouts/vetCenter/ExpandableOperatingStatus.tsx, src/templates/layouts/vetCenter/index.test.tsx, src/templates/layouts/vetCenter/index.tsx, src/types/formatted/vetCenter.ts
Ported [the old operating status template](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/includes/operating_status_expandable_alert.liquid) and modeled the new one after [the facility version](https://github.com/department-of-veterans-affairs/next-build/blob/db846cbc427efe5a32f23d99bc455aad8156a12f/src/templates/layouts/healthCareLocalFacility/OperatingStatus.tsx).
Closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/21568
- http://localhost:3999/greensboro-vet-center/ has a "Faciility notice" under the "main location" heading
- http://localhost:3999/yakima-valley-vet-center/ has a "Virtual care only" status
- http://localhost:3999/columbus-oh-vet-center/ has a temporary closure
=> Vets Center: Operating status flags

.github/workflows/content-release-prod.yml
This corrects the timing for Next Build Prod content release which was all off by 1 hour.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/21714
This code moves everything one hour earlier. Please check the existing times for Next Build Prod Content Release https://github.com/department-of-veterans-affairs/next-build/actions/workflows/content-release-prod.yml
These should be every 00 and 30 from 8 am to 8 pm ET, except for 3 pm, which should only be at 3:00 and not at 3:30 pm ET.
=> Fix timing for next build prod content release.

src/data/queries/accordion.ts, src/data/queries/featuredContent.ts, src/data/queries/tests/__snapshots__/vetCenterHealthServices.test.tsx.snap, src/data/queries/tests/__snapshots__/vetCenterOutstations.test.ts.snap, src/data/queries/tests/vetCenterHealthServices.test.tsx, src/data/queries/vetCenter.ts, src/data/queries/vetCenterHealthServices.ts, src/templates/components/vetCenterHealthServices/healthServices.stories.ts, src/templates/components/vetCenterHealthServicesList/index.tsx, src/templates/layouts/vetCenter/vetCenter.stories.ts, src/templates/layouts/vetCenterOutstation/vetCenterOutstation.stories.ts, src/types/formatted/vetCenterHealthServices.ts
There were a lot of different content fields that needed to be transformed so they'd pick up on things like phone number.
Closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/21464
Closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/21563
- http://localhost:3999/omaha-vet-center/ - "In the spotlight" section
- http://localhost:3999/boston-vet-center/ - "Where can I get help after hours?"
- http://localhost:3999/greensboro-vet-center/#item-suicide-prevention - "Suicide prevention" (https://github.com/department-of-veterans-affairs/va.gov-cms/issues/21563)
=> Vets Center: Transform HTML content for various content fields

envs/.env.dev, envs/.env.example, envs/.env.prod, envs/.env.staging, envs/.env.test
This pull request introduces environment variable updates to integrate Datadog RUM (Real User Monitoring) across various environments. The changes ensure consistent configuration for Datadog RUM in development, staging, testing, and example `.env` files.
* Added `NEXT_PUBLIC_DATADOG_RUM_SERVICE` and `NEXT_PUBLIC_DATADOG_RUM_SESSION_SAMPLE_RATE` to the following environment files:
- `envs/.env.dev` for development
- `envs/.env.staging` for staging
- `envs/.env.test` for testing
- `envs/.env.example` as a template/example
[Ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/21446)
Should be able to view Datadog RUM events for all nextjs server envs. This is dependent on infra PR request to be deployed. …
=> updated env vars for DD RUM

src/templates/layouts/vetCenter/index.tsx
We can just use the `Address` component here because it already does everything we want—and with valid HTML. The `<p>` tags surrounding the `<div>` tags was invalid HTML, which is what was causing the hydration errors.
Closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/21739
Loading http://localhost:3999/secaucus-vet-center/ should show no Next.js hydration errors (a big pop-up dialog, see ticket).
=> Vets Center: Fix the hydration error by fixing some invalid HTML

src/templates/layouts/vetCenter/index.test.tsx, src/templates/layouts/vetCenter/index.tsx
Adds the `ContentFooter` just like the other pages.
Closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/21565
Take a look at the bottom of http://localhost:3999/secaucus-vet-center/
I just noticed that the feedback button has different inner padding than production, but that's the case for this content footer component on other pages.
=> Vets Center: Add the `ContentFooter`

src/templates/layouts/vetCenter/SchemaScript.tsx, src/templates/layouts/vetCenter/__snapshots__/index.test.tsx.snap
Moving this one object fixed all validation errors, which is what @brianseek originally suggested. Decided to leave the rest of the detected differences with prod. Left a comment about the location one.
Closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/21836
Visit http://localhost:3999/secaucus-vet-center/ and paste the contents into the [schema.org validator](https://validator.schema.org/).
=> Vets Center: Fix schema.org validation errors

scripts/create-combined-reports.js
This ticket changes the header text of the csv report and removes the markdown report.
Closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/21460
```md
```
```
Of an initial 23842 pages, scanned total of 889550 links on 23842
Detected 1299 broken
```
```
http://www.va.gov/eastern-colorado-health-care/stories/navy-veteran-uses-art-to-help-self-provide-beauty-to-va-eastern-colorado-surrounding-area/,https://lonesomegoose.com/,404
http://www.va.gov/milwaukee-health-care/news-releases/three-historic-buildings-on-milwaukee-va-campus-to-be-renovated-for-service-of-veterans/,https://www.facebook.com/ajourneytothelightministries/,400
```
---
This section lists items that need to be checked or updated …
=> VACMS-21460: Update broken links report

src/templates/common/featuredContent/index.tsx, src/templates/layouts/vetCenter/index.tsx
Takes care of a legacy grid class that I missed in [the initial migration](https://github.com/department-of-veterans-affairs/next-build/pull/1186). The whole page was still wrapped in a class that isn't necessary anymore because the `usa-content` gives the page content a max width anyway. There's nothing I need to actually replace it with, which means we can get rid of a `div` and reduce the indentation in this file.
Closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/21948
The max page width on http://localhost:3999/secaucus-vet-center/ should look basically the same as it does in production.
=> Vets Center: Remove usa-width-three-fourths

src/data/queries/tests/__snapshots__/vamcHealthServicesListing.test.tsx.snap, src/data/queries/tests/vamcHealthServicesListing.test.tsx, src/data/queries/vamcHealthServicesListing.ts, src/templates/layouts/vamcHealthServicesListing/index.test.tsx, src/templates/layouts/vamcHealthServicesListing/index.tsx, src/types/formatted/vamcHealthServicesListing.ts
Adding the sidebar to this new template - health listings.
This pull request enhances the VAMC Health Services Listing page by integrating a sidebar navigation menu, updating data fetching and formatting logic, and improving test coverage for the new sidebar feature. The changes ensure that menu data is fetched, formatted, and injected into the page for use by a client-side widget.
**Sidebar Navigation Integration and Data Flow Updates:**
* Updated the data query (`vamcHealthServicesListing.ts`) to fetch the related menu via `getMenu` when available, and to include menu data in the returned result. The query params were also updated to include `field_system_menu` in the API request. [[1]](diffhunk://#diff-cd59258596d07741f82789df6648b29400e5efbfb4a2decd44d40dce8d4e6c83R10-R28) …
=> VACMS: 21867 - Health Listings sidebar logic and tests

src/components/pressReleaseListing/template.test.tsx, src/components/pressReleaseListing/template.tsx
Fixed the wrong text being used for when there are no press releases.
Closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/22104
http://localhost:3999/central-western-massachusetts-health-care/news-releases/
=> Fix the text for when there are no news releases

src/components/vamcSystemRegisterForCare/formatted-type.ts, src/components/vamcSystemRegisterForCare/mock.formatted.ts, src/components/vamcSystemRegisterForCare/query.test.ts, src/components/vamcSystemRegisterForCare/query.ts, src/components/vamcSystemRegisterForCare/template.test.tsx, src/components/vamcSystemRegisterForCare/template.tsx, src/types/drupal/field_type.d.ts
Adds the top-of-page CC content for the "Register for care" page.
Closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/21898
http://localhost:3999/richmond-health-care/register-for-care/
=> VAMC register for care: Top of page content

scripts/yarn/start.js
This is because we're not actually _compiling_ anything with this command, turns out. 🫠
=> Remove --turbopack from the start command

src/pages/_playground/api-explorer.tsx
When I'm doing local development, I often have tabs open for the API Explorer next to my other testing tabs, and I have a hard time telling which ones are which. This is a quick solution to that by giving the tab a title.
No ticket
=> Give API explorer tabs in the browser a real title

src/components/banner/__snapshots__/query.test.ts.snap, src/components/banner/query.ts
Until further notice, the main branch of this repo is locked. Pull requests should be made against the [integration-202510](https://github.com/department-of-veterans-affairs/next-build/tree/integration-202510) branch. 
Merges to the main branch for critical bugs or security updates are allowed. Please contact CMS Team in the [#platform-cms-team](https://dsva.slack.com/archives/CT4GZBM8F) channel if you need assistance. 
Formats the banner body value from `processed` data rather than `value`.
This pull request updates the banner data formatting logic to ensure the banner body is consistently converted to HTML before being output, improving data integrity and display. The main changes focus on using a utility function for HTML conversion and updating related imports and test snapshots. …
=> VACMS-22408: process wysiwyg body content on banner.

src/components/reactWidget/formatted-type.ts, src/components/reactWidget/query.ts, src/components/vamcSystemMedicalRecordsOffice/formatted-type.ts, src/components/vamcSystemMedicalRecordsOffice/mock.formatted.ts, src/components/vamcSystemMedicalRecordsOffice/query.test.ts, src/components/vamcSystemMedicalRecordsOffice/query.ts, src/components/vamcSystemMedicalRecordsOffice/template.test.tsx, src/components/vamcSystemMedicalRecordsOffice/template.tsx, src/lib/drupal/paragraphs.ts, src/types/drupal/field_type.d.ts, src/types/drupal/node.ts
Until further notice, the main branch of this repo is locked. Pull requests should be made against the [integration-202510](https://github.com/department-of-veterans-affairs/next-build/tree/integration-202510) branch. 
Merges to the main branch for critical bugs or security updates are allowed. Please contact CMS Team in the [#platform-cms-team](https://dsva.slack.com/archives/CT4GZBM8F) channel if you need assistance. 
We already had a component for rendering a`ReactWidget`, but as far as I can tell we've never used them until now. I had to make some adjustments, but it works now.
Closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/21978
http://localhost:3999/boston-health-care/medical-records-office
=> Medical records page: Add the React widget

src/lib/utils/getHtmlFromDrupalContent.ts, src/lib/utils/helpers.test.ts, src/lib/utils/helpers.ts
Until further notice, the main branch of this repo is locked. Pull requests should be made against the [integration-202510](https://github.com/department-of-veterans-affairs/next-build/tree/integration-202510) branch. 
Merges to the main branch for critical bugs or security updates are allowed. Please contact CMS Team in the [#platform-cms-team](https://dsva.slack.com/archives/CT4GZBM8F) channel if you need assistance. 
Converts action links created in Drupal wysiwyg to the web-component `va-link-action` in order to take advantage of the built in analytics. This also resolves the need to make changes in Drupal when the classes get deprecated. The conversion is optional, but on be default.
This pull request introduces a new utility function for converting specific action links in HTML …
=> VACMS-22304: missing analytics
